/**
 * @(#)JHistogram.java  1.0  January 27, 2008
 *
 * Copyright (c) 2008 Werner Randelshofer, Goldau, Switzerland.
 * All rights reserved.
 *
 * You may not use, copy or modify this file, except in compliance with the
 * license agreement you entered into with Werner Randelshofer.
 * For details see accompanying license terms.
 */
package ch.randelshofer.tree.demo;

import ch.randelshofer.tree.Colorizer;
import ch.randelshofer.tree.Weighter;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.util.Arrays;

/**
 * JHistogram.
 *
 * @author Werner Randelshofer
 * @version 1.0 JHistogram Created.
 */
public class JHistogram extends javax.swing.JComponent {

    private Colorizer colorizer;
    private Weighter weighter;
    private int[] histogram;

    /** Creates new form. */
    public JHistogram() {
        initComponents();
        // Activate tool tip text
        setToolTipText("");

    }

    public void setWeighter(Weighter newValue) {
        this.weighter = newValue;
        if (newValue != null) {
            histogram = weighter.getHistogram();
        } else {
            histogram = null;
        }
    }

    @Override
    public String getToolTipText(MouseEvent evt) {
        Insets insets = getInsets();

        Rectangle bounds = new Rectangle(insets.left, insets.top,
                getWidth() - insets.left - insets.right,
                getHeight() - insets.top - insets.bottom);


        int index = Math.min(histogram.length - 1, Math.max(0, (evt.getX() - bounds.x) * histogram.length / bounds.width));
        return weighter.getHistogramLabel(index);

    }

    @Override
    public Point getToolTipLocation(MouseEvent evt) {
        if (true) {
            return new Point(evt.getX(), getHeight()-2);
        }
        return null;
    }

    public void setColorizer(Colorizer newValue) {
        this.colorizer = newValue;
    }

    @Override
    public void paintComponent(Graphics gr) {
        Graphics2D g = (Graphics2D) gr;

        Insets insets = getInsets();

        if (histogram != null) {
            drawHistogram(g, new Rectangle(insets.left, insets.top,
                    getWidth() - insets.left - insets.right,
                    getHeight() - insets.top - insets.bottom));
        }
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(256, 40);
    }

    @Override
    public Dimension getMinimumSize() {
        return new Dimension(256, 40);
    }

    public void drawHistogram(Graphics2D g, Rectangle bounds) {
        if (colorizer != null) {
            /*for (int i = 0; i < bounds.width; i++) {
            float value = i / (float) (bounds.width);
            int x = bounds.x + i;
            g.setColor(colorizer.get(value));
            g.fillRect(x, bounds.y, 1, bounds.height);
            }*/
            for (int i = 0; i < histogram.length; i++) {
                float value = i / (float) (histogram.length);
                float nextValue = (i + 1) / (float) (histogram.length);
                int x = (int) (bounds.x + bounds.width * value);
                int nextX = (int) (bounds.x + bounds.width * nextValue);
                //System.out.print(histogram[i] + " " + height);
                g.setColor(colorizer.get(value));
                g.fillRect(x, bounds.y, nextX - x + 1, bounds.height);
            }
        }
        int maxCount = 0;
        for (int i = 0; i < histogram.length; i++) {
            maxCount = Math.max(maxCount, histogram[i]);
        }
        float scaleFactor = bounds.height / (float) maxCount;
        g.setColor(isEnabled()?Color.black:Color.GRAY);
        for (int i = 0; i < histogram.length; i++) {
            float value = i / (float) (histogram.length);
            float nextValue = (i + 1) / (float) (histogram.length);
            int x = (int) (bounds.x + bounds.width * value);
            int nextX = (int) (bounds.x + bounds.width * nextValue);
            int height = (int) Math.ceil(scaleFactor * histogram[i]);
            g.fillRect(x, bounds.y + bounds.height - height, nextX - x, height);
        }
        //System.out.println();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
