;; ============================== prooftrans ============================
;; Prover9 (64) version 2009-11A, November 2009.
;; Process 14746 was started by marty on kushiel,
;; Tue Oct 23 12:44:19 2012
;; The command was "prover9".
;; ============================== end of head ===========================

;; BEGINNING OF PROOF OBJECT
(
(4 (input) (Q) NIL)
(5 (input) (P (zero_for_ivy)) NIL)
(6 (input) (or (not (P v0)) (P (f v0))) NIL)
(7 (input) (or (not (P (f (f v0)))) (P (g v0))) NIL)
(8 (input) (or (not (P (g (zero_for_ivy)))) (or (not (P (f (zero_for_ivy)))) (or (not (P (g (g v0)))) (or (not (P (f (g v0)))) (not (Q)))))) NIL)
(30 (instantiate 8 ((v0 . v100))) (or (not (P (g (zero_for_ivy)))) (or (not (P (f (zero_for_ivy)))) (or (not (P (g (g v100)))) (or (not (P (f (g v100)))) (not (Q)))))) NIL)
(31 (resolve 4 () 30 (2 2 2 2)) (or (not (P (g (zero_for_ivy)))) (or (not (P (f (zero_for_ivy)))) (or (not (P (g (g v100)))) (not (P (f (g v100))))))) NIL)
(9 (instantiate 31 ((v100 . v0))) (or (not (P (g (zero_for_ivy)))) (or (not (P (f (zero_for_ivy)))) (or (not (P (g (g v0)))) (not (P (f (g v0))))))) NIL)
(32 (instantiate 6 ((v0 . (zero_for_ivy)))) (or (not (P (zero_for_ivy))) (P (f (zero_for_ivy)))) NIL)
(10 (resolve 32 (1) 5 ()) (P (f (zero_for_ivy))) NIL)
(33 (instantiate 9 ((v0 . v100))) (or (not (P (g (zero_for_ivy)))) (or (not (P (f (zero_for_ivy)))) (or (not (P (g (g v100)))) (not (P (f (g v100))))))) NIL)
(34 (resolve 10 () 33 (2 1)) (or (not (P (g (zero_for_ivy)))) (or (not (P (g (g v100)))) (not (P (f (g v100)))))) NIL)
(11 (instantiate 34 ((v100 . v0))) (or (not (P (g (zero_for_ivy)))) (or (not (P (g (g v0)))) (not (P (f (g v0)))))) NIL)
(35 (instantiate 6 ((v0 . (f (zero_for_ivy))))) (or (not (P (f (zero_for_ivy)))) (P (f (f (zero_for_ivy))))) NIL)
(12 (resolve 35 (1) 10 ()) (P (f (f (zero_for_ivy)))) NIL)
(36 (instantiate 11 ()) (or (not (P (g (zero_for_ivy)))) (or (not (P (g (g v0)))) (not (P (f (g v0)))))) NIL)
(37 (instantiate 7 ((v0 . (zero_for_ivy)))) (or (not (P (f (f (zero_for_ivy))))) (P (g (zero_for_ivy)))) NIL)
(13A (resolve 36 (1) 37 (2)) (or (not (P (g (g v0)))) (or (not (P (f (g v0)))) (not (P (f (f (zero_for_ivy))))))) NIL)
(38 (instantiate 13A ((v0 . v100))) (or (not (P (g (g v100)))) (or (not (P (f (g v100)))) (not (P (f (f (zero_for_ivy))))))) NIL)
(39 (resolve 12 () 38 (2 2)) (or (not (P (g (g v100)))) (not (P (f (g v100))))) NIL)
(13 (instantiate 39 ((v100 . v0))) (or (not (P (g (g v0)))) (not (P (f (g v0))))) NIL)
(40 (instantiate 13 ()) (or (not (P (g (g v0)))) (not (P (f (g v0))))) NIL)
(41 (instantiate 6 ((v0 . (g v0)))) (or (not (P (g v0))) (P (f (g v0)))) NIL)
(17 (resolve 40 (2) 41 (2)) (or (not (P (g (g v0)))) (not (P (g v0)))) NIL)
(42 (instantiate 17 ()) (or (not (P (g (g v0)))) (not (P (g v0)))) NIL)
(43 (instantiate 7 ((v0 . (g v0)))) (or (not (P (f (f (g v0))))) (P (g (g v0)))) NIL)
(18 (resolve 42 (1) 43 (2)) (or (not (P (g v0))) (not (P (f (f (g v0)))))) NIL)
(44 (instantiate 7 ((v0 . (zero_for_ivy)))) (or (not (P (f (f (zero_for_ivy))))) (P (g (zero_for_ivy)))) NIL)
(22 (resolve 44 (1) 12 ()) (P (g (zero_for_ivy))) NIL)
(45 (instantiate 18 ((v0 . (zero_for_ivy)))) (or (not (P (g (zero_for_ivy)))) (not (P (f (f (g (zero_for_ivy))))))) NIL)
(24 (resolve 22 () 45 (1)) (not (P (f (f (g (zero_for_ivy)))))) NIL)
(46 (instantiate 6 ((v0 . (g (zero_for_ivy))))) (or (not (P (g (zero_for_ivy)))) (P (f (g (zero_for_ivy))))) NIL)
(26 (resolve 46 (1) 22 ()) (P (f (g (zero_for_ivy)))) NIL)
(47 (instantiate 6 ((v0 . (f (g (zero_for_ivy)))))) (or (not (P (f (g (zero_for_ivy))))) (P (f (f (g (zero_for_ivy)))))) NIL)
(27A (resolve 47 (1) 26 ()) (P (f (f (g (zero_for_ivy))))) NIL)
(27 (resolve 24 () 27A ()) false NIL)
)
;; END OF PROOF OBJECT
