#!/bin/bash
# create .out-files from .s-files in Geoff's solution directory structure

for d in `ls -d Solutions/*`
do
  echo "Processing directory $d"
  for d2 in `ls -d $d/*`
  do
    for file in `ls $d2/*.s`
    do
      ./s_to_out < $file > $file.out
    done
  done
done
