#!/bin/bash
# create .out-files from .s-files in Geoff's solution directory structure
for file1 in *
do
  if [ -d "$file1" ]; then
    echo "processing directory $file1..."
    cd "$file1"
    for file2 in *
    do
      if [ -d "$file2" ]; then
        cd "$file2"
	for file3 in *.s
        do
          ../../s_to_out < $file3 > $file3.out
        done
	cd ..
      fi
    done
    cd ..
  fi
done
