;; ============================== prooftrans ============================
;; Prover9 (64) version 2009-11A, November 2009.
;; Process 24588 was started by marty on kushiel,
;; Thu Oct 25 15:29:00 2012
;; The command was "prover9".
;; ============================== end of head ===========================

;; BEGINNING OF PROOF OBJECT
(
(1 (input) (or (P v0) (or (P v1) (P v2))) NIL)
(2 (input) (or (not (P v0)) (or (not (P v1)) (not (P v2)))) NIL)
(8 (instantiate 1 ((v0 . v1))) (or (P v1) (or (P v1) (P v2))) NIL)
(9 (propositional 8) (or (P v1) (P v2)) NIL)
(3 (instantiate 9 ((v1 . v0) (v2 . v1))) (or (P v0) (P v1)) NIL)
(10 (instantiate 2 ((v0 . v1))) (or (not (P v1)) (or (not (P v1)) (not (P v2)))) NIL)
(11 (propositional 10) (or (not (P v1)) (not (P v2))) NIL)
(4 (instantiate 11 ((v1 . v0) (v2 . v1))) (or (not (P v0)) (not (P v1))) NIL)
(12 (instantiate 3 ((v0 . v1))) (or (P v1) (P v1)) NIL)
(13 (propositional 12) (P v1) NIL)
(5 (instantiate 13 ((v1 . v0))) (P v0) NIL)
(14 (instantiate 4 ((v0 . v1))) (or (not (P v1)) (not (P v1))) NIL)
(15 (propositional 14) (not (P v1)) NIL)
(6A (instantiate 15 ((v1 . v0))) (not (P v0)) NIL)
(16 (instantiate 5 ((v0 . v100))) (P v100) NIL)
(17 (instantiate 6A ((v0 . v100))) (not (P v100)) NIL)
(6 (resolve 16 () 17 ()) false NIL)
)
;; END OF PROOF OBJECT
