;; ============================== prooftrans ============================
;; Prover9 (64) version 2009-11A, November 2009.
;; Process 4181 was started by marty on kushiel,
;; Wed Oct 17 12:05:39 2012
;; The command was "prover9".
;; ============================== end of head ===========================

;; BEGINNING OF PROOF OBJECT
(
(1 (input) (or (not (A)) (or (not (B)) (not (C)))) NIL)
(2 (input) (A) NIL)
(3 (input) (B) NIL)
(4 (input) (C) NIL)
(5A (resolve 2 () 1 (1)) (or (not (B)) (not (C))) NIL)
(5B (resolve 3 () 5A (1)) (not (C)) NIL)
(5 (resolve 4 () 5B ()) false NIL)
)
;; END OF PROOF OBJECT
