;; ============================== prooftrans ============================
;; Prover9 (64) version 2009-11A, November 2009.
;; Process 9281 was started by marty on kushiel,
;; Mon Oct  8 15:07:56 2012
;; The command was "prover9".
;; ============================== end of head ===========================

;; BEGINNING OF PROOF OBJECT
(
(1 (input) (= (g v0) (f v0)) NIL)
(2 (input) (or (not (P v0)) (P (f v0))) NIL)
(3 (input) (P (a)) NIL)
(4 (input) (or (not (P (g (a)))) (not (P (g (a))))) NIL)
(10 (instantiate 1 ((v0 . (a)))) (= (g (a)) (f (a))) NIL)
(5A (paramod 10 (1) 4 (1 1 1)) (or (not (P (f (a)))) (not (P (g (a))))) NIL)
(11 (instantiate 1 ((v0 . (a)))) (= (g (a)) (f (a))) NIL)
(5B (paramod 11 (1) 5A (2 1 1)) (or (not (P (f (a)))) (not (P (f (a))))) NIL)
(5 (propositional 5B) (not (P (f (a)))) NIL)
(12 (instantiate 2 ((v0 . (a)))) (or (not (P (a))) (P (f (a)))) NIL)
(6A (resolve 12 (1) 3 ()) (P (f (a))) NIL)
(6 (resolve 5 () 6A ()) false NIL)
)
;; END OF PROOF OBJECT
