fof(a, axiom, p, file('Problems/correctchain_1000.p', a)).
fof(c, conjecture, p, file('Problems/correctchain_1000.p', c)).
fof(nc, negated_conjecture, ~ p, inference(negated_conjecture, [status(cth)], [c])).
fof(inf1000, plain, ~ p, inference(inf, [status(thm)], [nc])).
fof(inf999, plain, ~ p, inference(inf, [status(thm)], [inf1000])).
fof(inf998, plain, ~ p, inference(inf, [status(thm)], [inf999])).
fof(inf997, plain, ~ p, inference(inf, [status(thm)], [inf998])).
fof(inf996, plain, ~ p, inference(inf, [status(thm)], [inf997])).
fof(inf995, plain, ~ p, inference(inf, [status(thm)], [inf996])).
fof(inf994, plain, ~ p, inference(inf, [status(thm)], [inf995])).
fof(inf993, plain, ~ p, inference(inf, [status(thm)], [inf994])).
fof(inf992, plain, ~ p, inference(inf, [status(thm)], [inf993])).
fof(inf991, plain, ~ p, inference(inf, [status(thm)], [inf992])).
fof(inf990, plain, ~ p, inference(inf, [status(thm)], [inf991])).
fof(inf989, plain, ~ p, inference(inf, [status(thm)], [inf990])).
fof(inf988, plain, ~ p, inference(inf, [status(thm)], [inf989])).
fof(inf987, plain, ~ p, inference(inf, [status(thm)], [inf988])).
fof(inf986, plain, ~ p, inference(inf, [status(thm)], [inf987])).
fof(inf985, plain, ~ p, inference(inf, [status(thm)], [inf986])).
fof(inf984, plain, ~ p, inference(inf, [status(thm)], [inf985])).
fof(inf983, plain, ~ p, inference(inf, [status(thm)], [inf984])).
fof(inf982, plain, ~ p, inference(inf, [status(thm)], [inf983])).
fof(inf981, plain, ~ p, inference(inf, [status(thm)], [inf982])).
fof(inf980, plain, ~ p, inference(inf, [status(thm)], [inf981])).
fof(inf979, plain, ~ p, inference(inf, [status(thm)], [inf980])).
fof(inf978, plain, ~ p, inference(inf, [status(thm)], [inf979])).
fof(inf977, plain, ~ p, inference(inf, [status(thm)], [inf978])).
fof(inf976, plain, ~ p, inference(inf, [status(thm)], [inf977])).
fof(inf975, plain, ~ p, inference(inf, [status(thm)], [inf976])).
fof(inf974, plain, ~ p, inference(inf, [status(thm)], [inf975])).
fof(inf973, plain, ~ p, inference(inf, [status(thm)], [inf974])).
fof(inf972, plain, ~ p, inference(inf, [status(thm)], [inf973])).
fof(inf971, plain, ~ p, inference(inf, [status(thm)], [inf972])).
fof(inf970, plain, ~ p, inference(inf, [status(thm)], [inf971])).
fof(inf969, plain, ~ p, inference(inf, [status(thm)], [inf970])).
fof(inf968, plain, ~ p, inference(inf, [status(thm)], [inf969])).
fof(inf967, plain, ~ p, inference(inf, [status(thm)], [inf968])).
fof(inf966, plain, ~ p, inference(inf, [status(thm)], [inf967])).
fof(inf965, plain, ~ p, inference(inf, [status(thm)], [inf966])).
fof(inf964, plain, ~ p, inference(inf, [status(thm)], [inf965])).
fof(inf963, plain, ~ p, inference(inf, [status(thm)], [inf964])).
fof(inf962, plain, ~ p, inference(inf, [status(thm)], [inf963])).
fof(inf961, plain, ~ p, inference(inf, [status(thm)], [inf962])).
fof(inf960, plain, ~ p, inference(inf, [status(thm)], [inf961])).
fof(inf959, plain, ~ p, inference(inf, [status(thm)], [inf960])).
fof(inf958, plain, ~ p, inference(inf, [status(thm)], [inf959])).
fof(inf957, plain, ~ p, inference(inf, [status(thm)], [inf958])).
fof(inf956, plain, ~ p, inference(inf, [status(thm)], [inf957])).
fof(inf955, plain, ~ p, inference(inf, [status(thm)], [inf956])).
fof(inf954, plain, ~ p, inference(inf, [status(thm)], [inf955])).
fof(inf953, plain, ~ p, inference(inf, [status(thm)], [inf954])).
fof(inf952, plain, ~ p, inference(inf, [status(thm)], [inf953])).
fof(inf951, plain, ~ p, inference(inf, [status(thm)], [inf952])).
fof(inf950, plain, ~ p, inference(inf, [status(thm)], [inf951])).
fof(inf949, plain, ~ p, inference(inf, [status(thm)], [inf950])).
fof(inf948, plain, ~ p, inference(inf, [status(thm)], [inf949])).
fof(inf947, plain, ~ p, inference(inf, [status(thm)], [inf948])).
fof(inf946, plain, ~ p, inference(inf, [status(thm)], [inf947])).
fof(inf945, plain, ~ p, inference(inf, [status(thm)], [inf946])).
fof(inf944, plain, ~ p, inference(inf, [status(thm)], [inf945])).
fof(inf943, plain, ~ p, inference(inf, [status(thm)], [inf944])).
fof(inf942, plain, ~ p, inference(inf, [status(thm)], [inf943])).
fof(inf941, plain, ~ p, inference(inf, [status(thm)], [inf942])).
fof(inf940, plain, ~ p, inference(inf, [status(thm)], [inf941])).
fof(inf939, plain, ~ p, inference(inf, [status(thm)], [inf940])).
fof(inf938, plain, ~ p, inference(inf, [status(thm)], [inf939])).
fof(inf937, plain, ~ p, inference(inf, [status(thm)], [inf938])).
fof(inf936, plain, ~ p, inference(inf, [status(thm)], [inf937])).
fof(inf935, plain, ~ p, inference(inf, [status(thm)], [inf936])).
fof(inf934, plain, ~ p, inference(inf, [status(thm)], [inf935])).
fof(inf933, plain, ~ p, inference(inf, [status(thm)], [inf934])).
fof(inf932, plain, ~ p, inference(inf, [status(thm)], [inf933])).
fof(inf931, plain, ~ p, inference(inf, [status(thm)], [inf932])).
fof(inf930, plain, ~ p, inference(inf, [status(thm)], [inf931])).
fof(inf929, plain, ~ p, inference(inf, [status(thm)], [inf930])).
fof(inf928, plain, ~ p, inference(inf, [status(thm)], [inf929])).
fof(inf927, plain, ~ p, inference(inf, [status(thm)], [inf928])).
fof(inf926, plain, ~ p, inference(inf, [status(thm)], [inf927])).
fof(inf925, plain, ~ p, inference(inf, [status(thm)], [inf926])).
fof(inf924, plain, ~ p, inference(inf, [status(thm)], [inf925])).
fof(inf923, plain, ~ p, inference(inf, [status(thm)], [inf924])).
fof(inf922, plain, ~ p, inference(inf, [status(thm)], [inf923])).
fof(inf921, plain, ~ p, inference(inf, [status(thm)], [inf922])).
fof(inf920, plain, ~ p, inference(inf, [status(thm)], [inf921])).
fof(inf919, plain, ~ p, inference(inf, [status(thm)], [inf920])).
fof(inf918, plain, ~ p, inference(inf, [status(thm)], [inf919])).
fof(inf917, plain, ~ p, inference(inf, [status(thm)], [inf918])).
fof(inf916, plain, ~ p, inference(inf, [status(thm)], [inf917])).
fof(inf915, plain, ~ p, inference(inf, [status(thm)], [inf916])).
fof(inf914, plain, ~ p, inference(inf, [status(thm)], [inf915])).
fof(inf913, plain, ~ p, inference(inf, [status(thm)], [inf914])).
fof(inf912, plain, ~ p, inference(inf, [status(thm)], [inf913])).
fof(inf911, plain, ~ p, inference(inf, [status(thm)], [inf912])).
fof(inf910, plain, ~ p, inference(inf, [status(thm)], [inf911])).
fof(inf909, plain, ~ p, inference(inf, [status(thm)], [inf910])).
fof(inf908, plain, ~ p, inference(inf, [status(thm)], [inf909])).
fof(inf907, plain, ~ p, inference(inf, [status(thm)], [inf908])).
fof(inf906, plain, ~ p, inference(inf, [status(thm)], [inf907])).
fof(inf905, plain, ~ p, inference(inf, [status(thm)], [inf906])).
fof(inf904, plain, ~ p, inference(inf, [status(thm)], [inf905])).
fof(inf903, plain, ~ p, inference(inf, [status(thm)], [inf904])).
fof(inf902, plain, ~ p, inference(inf, [status(thm)], [inf903])).
fof(inf901, plain, ~ p, inference(inf, [status(thm)], [inf902])).
fof(inf900, plain, ~ p, inference(inf, [status(thm)], [inf901])).
fof(inf899, plain, ~ p, inference(inf, [status(thm)], [inf900])).
fof(inf898, plain, ~ p, inference(inf, [status(thm)], [inf899])).
fof(inf897, plain, ~ p, inference(inf, [status(thm)], [inf898])).
fof(inf896, plain, ~ p, inference(inf, [status(thm)], [inf897])).
fof(inf895, plain, ~ p, inference(inf, [status(thm)], [inf896])).
fof(inf894, plain, ~ p, inference(inf, [status(thm)], [inf895])).
fof(inf893, plain, ~ p, inference(inf, [status(thm)], [inf894])).
fof(inf892, plain, ~ p, inference(inf, [status(thm)], [inf893])).
fof(inf891, plain, ~ p, inference(inf, [status(thm)], [inf892])).
fof(inf890, plain, ~ p, inference(inf, [status(thm)], [inf891])).
fof(inf889, plain, ~ p, inference(inf, [status(thm)], [inf890])).
fof(inf888, plain, ~ p, inference(inf, [status(thm)], [inf889])).
fof(inf887, plain, ~ p, inference(inf, [status(thm)], [inf888])).
fof(inf886, plain, ~ p, inference(inf, [status(thm)], [inf887])).
fof(inf885, plain, ~ p, inference(inf, [status(thm)], [inf886])).
fof(inf884, plain, ~ p, inference(inf, [status(thm)], [inf885])).
fof(inf883, plain, ~ p, inference(inf, [status(thm)], [inf884])).
fof(inf882, plain, ~ p, inference(inf, [status(thm)], [inf883])).
fof(inf881, plain, ~ p, inference(inf, [status(thm)], [inf882])).
fof(inf880, plain, ~ p, inference(inf, [status(thm)], [inf881])).
fof(inf879, plain, ~ p, inference(inf, [status(thm)], [inf880])).
fof(inf878, plain, ~ p, inference(inf, [status(thm)], [inf879])).
fof(inf877, plain, ~ p, inference(inf, [status(thm)], [inf878])).
fof(inf876, plain, ~ p, inference(inf, [status(thm)], [inf877])).
fof(inf875, plain, ~ p, inference(inf, [status(thm)], [inf876])).
fof(inf874, plain, ~ p, inference(inf, [status(thm)], [inf875])).
fof(inf873, plain, ~ p, inference(inf, [status(thm)], [inf874])).
fof(inf872, plain, ~ p, inference(inf, [status(thm)], [inf873])).
fof(inf871, plain, ~ p, inference(inf, [status(thm)], [inf872])).
fof(inf870, plain, ~ p, inference(inf, [status(thm)], [inf871])).
fof(inf869, plain, ~ p, inference(inf, [status(thm)], [inf870])).
fof(inf868, plain, ~ p, inference(inf, [status(thm)], [inf869])).
fof(inf867, plain, ~ p, inference(inf, [status(thm)], [inf868])).
fof(inf866, plain, ~ p, inference(inf, [status(thm)], [inf867])).
fof(inf865, plain, ~ p, inference(inf, [status(thm)], [inf866])).
fof(inf864, plain, ~ p, inference(inf, [status(thm)], [inf865])).
fof(inf863, plain, ~ p, inference(inf, [status(thm)], [inf864])).
fof(inf862, plain, ~ p, inference(inf, [status(thm)], [inf863])).
fof(inf861, plain, ~ p, inference(inf, [status(thm)], [inf862])).
fof(inf860, plain, ~ p, inference(inf, [status(thm)], [inf861])).
fof(inf859, plain, ~ p, inference(inf, [status(thm)], [inf860])).
fof(inf858, plain, ~ p, inference(inf, [status(thm)], [inf859])).
fof(inf857, plain, ~ p, inference(inf, [status(thm)], [inf858])).
fof(inf856, plain, ~ p, inference(inf, [status(thm)], [inf857])).
fof(inf855, plain, ~ p, inference(inf, [status(thm)], [inf856])).
fof(inf854, plain, ~ p, inference(inf, [status(thm)], [inf855])).
fof(inf853, plain, ~ p, inference(inf, [status(thm)], [inf854])).
fof(inf852, plain, ~ p, inference(inf, [status(thm)], [inf853])).
fof(inf851, plain, ~ p, inference(inf, [status(thm)], [inf852])).
fof(inf850, plain, ~ p, inference(inf, [status(thm)], [inf851])).
fof(inf849, plain, ~ p, inference(inf, [status(thm)], [inf850])).
fof(inf848, plain, ~ p, inference(inf, [status(thm)], [inf849])).
fof(inf847, plain, ~ p, inference(inf, [status(thm)], [inf848])).
fof(inf846, plain, ~ p, inference(inf, [status(thm)], [inf847])).
fof(inf845, plain, ~ p, inference(inf, [status(thm)], [inf846])).
fof(inf844, plain, ~ p, inference(inf, [status(thm)], [inf845])).
fof(inf843, plain, ~ p, inference(inf, [status(thm)], [inf844])).
fof(inf842, plain, ~ p, inference(inf, [status(thm)], [inf843])).
fof(inf841, plain, ~ p, inference(inf, [status(thm)], [inf842])).
fof(inf840, plain, ~ p, inference(inf, [status(thm)], [inf841])).
fof(inf839, plain, ~ p, inference(inf, [status(thm)], [inf840])).
fof(inf838, plain, ~ p, inference(inf, [status(thm)], [inf839])).
fof(inf837, plain, ~ p, inference(inf, [status(thm)], [inf838])).
fof(inf836, plain, ~ p, inference(inf, [status(thm)], [inf837])).
fof(inf835, plain, ~ p, inference(inf, [status(thm)], [inf836])).
fof(inf834, plain, ~ p, inference(inf, [status(thm)], [inf835])).
fof(inf833, plain, ~ p, inference(inf, [status(thm)], [inf834])).
fof(inf832, plain, ~ p, inference(inf, [status(thm)], [inf833])).
fof(inf831, plain, ~ p, inference(inf, [status(thm)], [inf832])).
fof(inf830, plain, ~ p, inference(inf, [status(thm)], [inf831])).
fof(inf829, plain, ~ p, inference(inf, [status(thm)], [inf830])).
fof(inf828, plain, ~ p, inference(inf, [status(thm)], [inf829])).
fof(inf827, plain, ~ p, inference(inf, [status(thm)], [inf828])).
fof(inf826, plain, ~ p, inference(inf, [status(thm)], [inf827])).
fof(inf825, plain, ~ p, inference(inf, [status(thm)], [inf826])).
fof(inf824, plain, ~ p, inference(inf, [status(thm)], [inf825])).
fof(inf823, plain, ~ p, inference(inf, [status(thm)], [inf824])).
fof(inf822, plain, ~ p, inference(inf, [status(thm)], [inf823])).
fof(inf821, plain, ~ p, inference(inf, [status(thm)], [inf822])).
fof(inf820, plain, ~ p, inference(inf, [status(thm)], [inf821])).
fof(inf819, plain, ~ p, inference(inf, [status(thm)], [inf820])).
fof(inf818, plain, ~ p, inference(inf, [status(thm)], [inf819])).
fof(inf817, plain, ~ p, inference(inf, [status(thm)], [inf818])).
fof(inf816, plain, ~ p, inference(inf, [status(thm)], [inf817])).
fof(inf815, plain, ~ p, inference(inf, [status(thm)], [inf816])).
fof(inf814, plain, ~ p, inference(inf, [status(thm)], [inf815])).
fof(inf813, plain, ~ p, inference(inf, [status(thm)], [inf814])).
fof(inf812, plain, ~ p, inference(inf, [status(thm)], [inf813])).
fof(inf811, plain, ~ p, inference(inf, [status(thm)], [inf812])).
fof(inf810, plain, ~ p, inference(inf, [status(thm)], [inf811])).
fof(inf809, plain, ~ p, inference(inf, [status(thm)], [inf810])).
fof(inf808, plain, ~ p, inference(inf, [status(thm)], [inf809])).
fof(inf807, plain, ~ p, inference(inf, [status(thm)], [inf808])).
fof(inf806, plain, ~ p, inference(inf, [status(thm)], [inf807])).
fof(inf805, plain, ~ p, inference(inf, [status(thm)], [inf806])).
fof(inf804, plain, ~ p, inference(inf, [status(thm)], [inf805])).
fof(inf803, plain, ~ p, inference(inf, [status(thm)], [inf804])).
fof(inf802, plain, ~ p, inference(inf, [status(thm)], [inf803])).
fof(inf801, plain, ~ p, inference(inf, [status(thm)], [inf802])).
fof(inf800, plain, ~ p, inference(inf, [status(thm)], [inf801])).
fof(inf799, plain, ~ p, inference(inf, [status(thm)], [inf800])).
fof(inf798, plain, ~ p, inference(inf, [status(thm)], [inf799])).
fof(inf797, plain, ~ p, inference(inf, [status(thm)], [inf798])).
fof(inf796, plain, ~ p, inference(inf, [status(thm)], [inf797])).
fof(inf795, plain, ~ p, inference(inf, [status(thm)], [inf796])).
fof(inf794, plain, ~ p, inference(inf, [status(thm)], [inf795])).
fof(inf793, plain, ~ p, inference(inf, [status(thm)], [inf794])).
fof(inf792, plain, ~ p, inference(inf, [status(thm)], [inf793])).
fof(inf791, plain, ~ p, inference(inf, [status(thm)], [inf792])).
fof(inf790, plain, ~ p, inference(inf, [status(thm)], [inf791])).
fof(inf789, plain, ~ p, inference(inf, [status(thm)], [inf790])).
fof(inf788, plain, ~ p, inference(inf, [status(thm)], [inf789])).
fof(inf787, plain, ~ p, inference(inf, [status(thm)], [inf788])).
fof(inf786, plain, ~ p, inference(inf, [status(thm)], [inf787])).
fof(inf785, plain, ~ p, inference(inf, [status(thm)], [inf786])).
fof(inf784, plain, ~ p, inference(inf, [status(thm)], [inf785])).
fof(inf783, plain, ~ p, inference(inf, [status(thm)], [inf784])).
fof(inf782, plain, ~ p, inference(inf, [status(thm)], [inf783])).
fof(inf781, plain, ~ p, inference(inf, [status(thm)], [inf782])).
fof(inf780, plain, ~ p, inference(inf, [status(thm)], [inf781])).
fof(inf779, plain, ~ p, inference(inf, [status(thm)], [inf780])).
fof(inf778, plain, ~ p, inference(inf, [status(thm)], [inf779])).
fof(inf777, plain, ~ p, inference(inf, [status(thm)], [inf778])).
fof(inf776, plain, ~ p, inference(inf, [status(thm)], [inf777])).
fof(inf775, plain, ~ p, inference(inf, [status(thm)], [inf776])).
fof(inf774, plain, ~ p, inference(inf, [status(thm)], [inf775])).
fof(inf773, plain, ~ p, inference(inf, [status(thm)], [inf774])).
fof(inf772, plain, ~ p, inference(inf, [status(thm)], [inf773])).
fof(inf771, plain, ~ p, inference(inf, [status(thm)], [inf772])).
fof(inf770, plain, ~ p, inference(inf, [status(thm)], [inf771])).
fof(inf769, plain, ~ p, inference(inf, [status(thm)], [inf770])).
fof(inf768, plain, ~ p, inference(inf, [status(thm)], [inf769])).
fof(inf767, plain, ~ p, inference(inf, [status(thm)], [inf768])).
fof(inf766, plain, ~ p, inference(inf, [status(thm)], [inf767])).
fof(inf765, plain, ~ p, inference(inf, [status(thm)], [inf766])).
fof(inf764, plain, ~ p, inference(inf, [status(thm)], [inf765])).
fof(inf763, plain, ~ p, inference(inf, [status(thm)], [inf764])).
fof(inf762, plain, ~ p, inference(inf, [status(thm)], [inf763])).
fof(inf761, plain, ~ p, inference(inf, [status(thm)], [inf762])).
fof(inf760, plain, ~ p, inference(inf, [status(thm)], [inf761])).
fof(inf759, plain, ~ p, inference(inf, [status(thm)], [inf760])).
fof(inf758, plain, ~ p, inference(inf, [status(thm)], [inf759])).
fof(inf757, plain, ~ p, inference(inf, [status(thm)], [inf758])).
fof(inf756, plain, ~ p, inference(inf, [status(thm)], [inf757])).
fof(inf755, plain, ~ p, inference(inf, [status(thm)], [inf756])).
fof(inf754, plain, ~ p, inference(inf, [status(thm)], [inf755])).
fof(inf753, plain, ~ p, inference(inf, [status(thm)], [inf754])).
fof(inf752, plain, ~ p, inference(inf, [status(thm)], [inf753])).
fof(inf751, plain, ~ p, inference(inf, [status(thm)], [inf752])).
fof(inf750, plain, ~ p, inference(inf, [status(thm)], [inf751])).
fof(inf749, plain, ~ p, inference(inf, [status(thm)], [inf750])).
fof(inf748, plain, ~ p, inference(inf, [status(thm)], [inf749])).
fof(inf747, plain, ~ p, inference(inf, [status(thm)], [inf748])).
fof(inf746, plain, ~ p, inference(inf, [status(thm)], [inf747])).
fof(inf745, plain, ~ p, inference(inf, [status(thm)], [inf746])).
fof(inf744, plain, ~ p, inference(inf, [status(thm)], [inf745])).
fof(inf743, plain, ~ p, inference(inf, [status(thm)], [inf744])).
fof(inf742, plain, ~ p, inference(inf, [status(thm)], [inf743])).
fof(inf741, plain, ~ p, inference(inf, [status(thm)], [inf742])).
fof(inf740, plain, ~ p, inference(inf, [status(thm)], [inf741])).
fof(inf739, plain, ~ p, inference(inf, [status(thm)], [inf740])).
fof(inf738, plain, ~ p, inference(inf, [status(thm)], [inf739])).
fof(inf737, plain, ~ p, inference(inf, [status(thm)], [inf738])).
fof(inf736, plain, ~ p, inference(inf, [status(thm)], [inf737])).
fof(inf735, plain, ~ p, inference(inf, [status(thm)], [inf736])).
fof(inf734, plain, ~ p, inference(inf, [status(thm)], [inf735])).
fof(inf733, plain, ~ p, inference(inf, [status(thm)], [inf734])).
fof(inf732, plain, ~ p, inference(inf, [status(thm)], [inf733])).
fof(inf731, plain, ~ p, inference(inf, [status(thm)], [inf732])).
fof(inf730, plain, ~ p, inference(inf, [status(thm)], [inf731])).
fof(inf729, plain, ~ p, inference(inf, [status(thm)], [inf730])).
fof(inf728, plain, ~ p, inference(inf, [status(thm)], [inf729])).
fof(inf727, plain, ~ p, inference(inf, [status(thm)], [inf728])).
fof(inf726, plain, ~ p, inference(inf, [status(thm)], [inf727])).
fof(inf725, plain, ~ p, inference(inf, [status(thm)], [inf726])).
fof(inf724, plain, ~ p, inference(inf, [status(thm)], [inf725])).
fof(inf723, plain, ~ p, inference(inf, [status(thm)], [inf724])).
fof(inf722, plain, ~ p, inference(inf, [status(thm)], [inf723])).
fof(inf721, plain, ~ p, inference(inf, [status(thm)], [inf722])).
fof(inf720, plain, ~ p, inference(inf, [status(thm)], [inf721])).
fof(inf719, plain, ~ p, inference(inf, [status(thm)], [inf720])).
fof(inf718, plain, ~ p, inference(inf, [status(thm)], [inf719])).
fof(inf717, plain, ~ p, inference(inf, [status(thm)], [inf718])).
fof(inf716, plain, ~ p, inference(inf, [status(thm)], [inf717])).
fof(inf715, plain, ~ p, inference(inf, [status(thm)], [inf716])).
fof(inf714, plain, ~ p, inference(inf, [status(thm)], [inf715])).
fof(inf713, plain, ~ p, inference(inf, [status(thm)], [inf714])).
fof(inf712, plain, ~ p, inference(inf, [status(thm)], [inf713])).
fof(inf711, plain, ~ p, inference(inf, [status(thm)], [inf712])).
fof(inf710, plain, ~ p, inference(inf, [status(thm)], [inf711])).
fof(inf709, plain, ~ p, inference(inf, [status(thm)], [inf710])).
fof(inf708, plain, ~ p, inference(inf, [status(thm)], [inf709])).
fof(inf707, plain, ~ p, inference(inf, [status(thm)], [inf708])).
fof(inf706, plain, ~ p, inference(inf, [status(thm)], [inf707])).
fof(inf705, plain, ~ p, inference(inf, [status(thm)], [inf706])).
fof(inf704, plain, ~ p, inference(inf, [status(thm)], [inf705])).
fof(inf703, plain, ~ p, inference(inf, [status(thm)], [inf704])).
fof(inf702, plain, ~ p, inference(inf, [status(thm)], [inf703])).
fof(inf701, plain, ~ p, inference(inf, [status(thm)], [inf702])).
fof(inf700, plain, ~ p, inference(inf, [status(thm)], [inf701])).
fof(inf699, plain, ~ p, inference(inf, [status(thm)], [inf700])).
fof(inf698, plain, ~ p, inference(inf, [status(thm)], [inf699])).
fof(inf697, plain, ~ p, inference(inf, [status(thm)], [inf698])).
fof(inf696, plain, ~ p, inference(inf, [status(thm)], [inf697])).
fof(inf695, plain, ~ p, inference(inf, [status(thm)], [inf696])).
fof(inf694, plain, ~ p, inference(inf, [status(thm)], [inf695])).
fof(inf693, plain, ~ p, inference(inf, [status(thm)], [inf694])).
fof(inf692, plain, ~ p, inference(inf, [status(thm)], [inf693])).
fof(inf691, plain, ~ p, inference(inf, [status(thm)], [inf692])).
fof(inf690, plain, ~ p, inference(inf, [status(thm)], [inf691])).
fof(inf689, plain, ~ p, inference(inf, [status(thm)], [inf690])).
fof(inf688, plain, ~ p, inference(inf, [status(thm)], [inf689])).
fof(inf687, plain, ~ p, inference(inf, [status(thm)], [inf688])).
fof(inf686, plain, ~ p, inference(inf, [status(thm)], [inf687])).
fof(inf685, plain, ~ p, inference(inf, [status(thm)], [inf686])).
fof(inf684, plain, ~ p, inference(inf, [status(thm)], [inf685])).
fof(inf683, plain, ~ p, inference(inf, [status(thm)], [inf684])).
fof(inf682, plain, ~ p, inference(inf, [status(thm)], [inf683])).
fof(inf681, plain, ~ p, inference(inf, [status(thm)], [inf682])).
fof(inf680, plain, ~ p, inference(inf, [status(thm)], [inf681])).
fof(inf679, plain, ~ p, inference(inf, [status(thm)], [inf680])).
fof(inf678, plain, ~ p, inference(inf, [status(thm)], [inf679])).
fof(inf677, plain, ~ p, inference(inf, [status(thm)], [inf678])).
fof(inf676, plain, ~ p, inference(inf, [status(thm)], [inf677])).
fof(inf675, plain, ~ p, inference(inf, [status(thm)], [inf676])).
fof(inf674, plain, ~ p, inference(inf, [status(thm)], [inf675])).
fof(inf673, plain, ~ p, inference(inf, [status(thm)], [inf674])).
fof(inf672, plain, ~ p, inference(inf, [status(thm)], [inf673])).
fof(inf671, plain, ~ p, inference(inf, [status(thm)], [inf672])).
fof(inf670, plain, ~ p, inference(inf, [status(thm)], [inf671])).
fof(inf669, plain, ~ p, inference(inf, [status(thm)], [inf670])).
fof(inf668, plain, ~ p, inference(inf, [status(thm)], [inf669])).
fof(inf667, plain, ~ p, inference(inf, [status(thm)], [inf668])).
fof(inf666, plain, ~ p, inference(inf, [status(thm)], [inf667])).
fof(inf665, plain, ~ p, inference(inf, [status(thm)], [inf666])).
fof(inf664, plain, ~ p, inference(inf, [status(thm)], [inf665])).
fof(inf663, plain, ~ p, inference(inf, [status(thm)], [inf664])).
fof(inf662, plain, ~ p, inference(inf, [status(thm)], [inf663])).
fof(inf661, plain, ~ p, inference(inf, [status(thm)], [inf662])).
fof(inf660, plain, ~ p, inference(inf, [status(thm)], [inf661])).
fof(inf659, plain, ~ p, inference(inf, [status(thm)], [inf660])).
fof(inf658, plain, ~ p, inference(inf, [status(thm)], [inf659])).
fof(inf657, plain, ~ p, inference(inf, [status(thm)], [inf658])).
fof(inf656, plain, ~ p, inference(inf, [status(thm)], [inf657])).
fof(inf655, plain, ~ p, inference(inf, [status(thm)], [inf656])).
fof(inf654, plain, ~ p, inference(inf, [status(thm)], [inf655])).
fof(inf653, plain, ~ p, inference(inf, [status(thm)], [inf654])).
fof(inf652, plain, ~ p, inference(inf, [status(thm)], [inf653])).
fof(inf651, plain, ~ p, inference(inf, [status(thm)], [inf652])).
fof(inf650, plain, ~ p, inference(inf, [status(thm)], [inf651])).
fof(inf649, plain, ~ p, inference(inf, [status(thm)], [inf650])).
fof(inf648, plain, ~ p, inference(inf, [status(thm)], [inf649])).
fof(inf647, plain, ~ p, inference(inf, [status(thm)], [inf648])).
fof(inf646, plain, ~ p, inference(inf, [status(thm)], [inf647])).
fof(inf645, plain, ~ p, inference(inf, [status(thm)], [inf646])).
fof(inf644, plain, ~ p, inference(inf, [status(thm)], [inf645])).
fof(inf643, plain, ~ p, inference(inf, [status(thm)], [inf644])).
fof(inf642, plain, ~ p, inference(inf, [status(thm)], [inf643])).
fof(inf641, plain, ~ p, inference(inf, [status(thm)], [inf642])).
fof(inf640, plain, ~ p, inference(inf, [status(thm)], [inf641])).
fof(inf639, plain, ~ p, inference(inf, [status(thm)], [inf640])).
fof(inf638, plain, ~ p, inference(inf, [status(thm)], [inf639])).
fof(inf637, plain, ~ p, inference(inf, [status(thm)], [inf638])).
fof(inf636, plain, ~ p, inference(inf, [status(thm)], [inf637])).
fof(inf635, plain, ~ p, inference(inf, [status(thm)], [inf636])).
fof(inf634, plain, ~ p, inference(inf, [status(thm)], [inf635])).
fof(inf633, plain, ~ p, inference(inf, [status(thm)], [inf634])).
fof(inf632, plain, ~ p, inference(inf, [status(thm)], [inf633])).
fof(inf631, plain, ~ p, inference(inf, [status(thm)], [inf632])).
fof(inf630, plain, ~ p, inference(inf, [status(thm)], [inf631])).
fof(inf629, plain, ~ p, inference(inf, [status(thm)], [inf630])).
fof(inf628, plain, ~ p, inference(inf, [status(thm)], [inf629])).
fof(inf627, plain, ~ p, inference(inf, [status(thm)], [inf628])).
fof(inf626, plain, ~ p, inference(inf, [status(thm)], [inf627])).
fof(inf625, plain, ~ p, inference(inf, [status(thm)], [inf626])).
fof(inf624, plain, ~ p, inference(inf, [status(thm)], [inf625])).
fof(inf623, plain, ~ p, inference(inf, [status(thm)], [inf624])).
fof(inf622, plain, ~ p, inference(inf, [status(thm)], [inf623])).
fof(inf621, plain, ~ p, inference(inf, [status(thm)], [inf622])).
fof(inf620, plain, ~ p, inference(inf, [status(thm)], [inf621])).
fof(inf619, plain, ~ p, inference(inf, [status(thm)], [inf620])).
fof(inf618, plain, ~ p, inference(inf, [status(thm)], [inf619])).
fof(inf617, plain, ~ p, inference(inf, [status(thm)], [inf618])).
fof(inf616, plain, ~ p, inference(inf, [status(thm)], [inf617])).
fof(inf615, plain, ~ p, inference(inf, [status(thm)], [inf616])).
fof(inf614, plain, ~ p, inference(inf, [status(thm)], [inf615])).
fof(inf613, plain, ~ p, inference(inf, [status(thm)], [inf614])).
fof(inf612, plain, ~ p, inference(inf, [status(thm)], [inf613])).
fof(inf611, plain, ~ p, inference(inf, [status(thm)], [inf612])).
fof(inf610, plain, ~ p, inference(inf, [status(thm)], [inf611])).
fof(inf609, plain, ~ p, inference(inf, [status(thm)], [inf610])).
fof(inf608, plain, ~ p, inference(inf, [status(thm)], [inf609])).
fof(inf607, plain, ~ p, inference(inf, [status(thm)], [inf608])).
fof(inf606, plain, ~ p, inference(inf, [status(thm)], [inf607])).
fof(inf605, plain, ~ p, inference(inf, [status(thm)], [inf606])).
fof(inf604, plain, ~ p, inference(inf, [status(thm)], [inf605])).
fof(inf603, plain, ~ p, inference(inf, [status(thm)], [inf604])).
fof(inf602, plain, ~ p, inference(inf, [status(thm)], [inf603])).
fof(inf601, plain, ~ p, inference(inf, [status(thm)], [inf602])).
fof(inf600, plain, ~ p, inference(inf, [status(thm)], [inf601])).
fof(inf599, plain, ~ p, inference(inf, [status(thm)], [inf600])).
fof(inf598, plain, ~ p, inference(inf, [status(thm)], [inf599])).
fof(inf597, plain, ~ p, inference(inf, [status(thm)], [inf598])).
fof(inf596, plain, ~ p, inference(inf, [status(thm)], [inf597])).
fof(inf595, plain, ~ p, inference(inf, [status(thm)], [inf596])).
fof(inf594, plain, ~ p, inference(inf, [status(thm)], [inf595])).
fof(inf593, plain, ~ p, inference(inf, [status(thm)], [inf594])).
fof(inf592, plain, ~ p, inference(inf, [status(thm)], [inf593])).
fof(inf591, plain, ~ p, inference(inf, [status(thm)], [inf592])).
fof(inf590, plain, ~ p, inference(inf, [status(thm)], [inf591])).
fof(inf589, plain, ~ p, inference(inf, [status(thm)], [inf590])).
fof(inf588, plain, ~ p, inference(inf, [status(thm)], [inf589])).
fof(inf587, plain, ~ p, inference(inf, [status(thm)], [inf588])).
fof(inf586, plain, ~ p, inference(inf, [status(thm)], [inf587])).
fof(inf585, plain, ~ p, inference(inf, [status(thm)], [inf586])).
fof(inf584, plain, ~ p, inference(inf, [status(thm)], [inf585])).
fof(inf583, plain, ~ p, inference(inf, [status(thm)], [inf584])).
fof(inf582, plain, ~ p, inference(inf, [status(thm)], [inf583])).
fof(inf581, plain, ~ p, inference(inf, [status(thm)], [inf582])).
fof(inf580, plain, ~ p, inference(inf, [status(thm)], [inf581])).
fof(inf579, plain, ~ p, inference(inf, [status(thm)], [inf580])).
fof(inf578, plain, ~ p, inference(inf, [status(thm)], [inf579])).
fof(inf577, plain, ~ p, inference(inf, [status(thm)], [inf578])).
fof(inf576, plain, ~ p, inference(inf, [status(thm)], [inf577])).
fof(inf575, plain, ~ p, inference(inf, [status(thm)], [inf576])).
fof(inf574, plain, ~ p, inference(inf, [status(thm)], [inf575])).
fof(inf573, plain, ~ p, inference(inf, [status(thm)], [inf574])).
fof(inf572, plain, ~ p, inference(inf, [status(thm)], [inf573])).
fof(inf571, plain, ~ p, inference(inf, [status(thm)], [inf572])).
fof(inf570, plain, ~ p, inference(inf, [status(thm)], [inf571])).
fof(inf569, plain, ~ p, inference(inf, [status(thm)], [inf570])).
fof(inf568, plain, ~ p, inference(inf, [status(thm)], [inf569])).
fof(inf567, plain, ~ p, inference(inf, [status(thm)], [inf568])).
fof(inf566, plain, ~ p, inference(inf, [status(thm)], [inf567])).
fof(inf565, plain, ~ p, inference(inf, [status(thm)], [inf566])).
fof(inf564, plain, ~ p, inference(inf, [status(thm)], [inf565])).
fof(inf563, plain, ~ p, inference(inf, [status(thm)], [inf564])).
fof(inf562, plain, ~ p, inference(inf, [status(thm)], [inf563])).
fof(inf561, plain, ~ p, inference(inf, [status(thm)], [inf562])).
fof(inf560, plain, ~ p, inference(inf, [status(thm)], [inf561])).
fof(inf559, plain, ~ p, inference(inf, [status(thm)], [inf560])).
fof(inf558, plain, ~ p, inference(inf, [status(thm)], [inf559])).
fof(inf557, plain, ~ p, inference(inf, [status(thm)], [inf558])).
fof(inf556, plain, ~ p, inference(inf, [status(thm)], [inf557])).
fof(inf555, plain, ~ p, inference(inf, [status(thm)], [inf556])).
fof(inf554, plain, ~ p, inference(inf, [status(thm)], [inf555])).
fof(inf553, plain, ~ p, inference(inf, [status(thm)], [inf554])).
fof(inf552, plain, ~ p, inference(inf, [status(thm)], [inf553])).
fof(inf551, plain, ~ p, inference(inf, [status(thm)], [inf552])).
fof(inf550, plain, ~ p, inference(inf, [status(thm)], [inf551])).
fof(inf549, plain, ~ p, inference(inf, [status(thm)], [inf550])).
fof(inf548, plain, ~ p, inference(inf, [status(thm)], [inf549])).
fof(inf547, plain, ~ p, inference(inf, [status(thm)], [inf548])).
fof(inf546, plain, ~ p, inference(inf, [status(thm)], [inf547])).
fof(inf545, plain, ~ p, inference(inf, [status(thm)], [inf546])).
fof(inf544, plain, ~ p, inference(inf, [status(thm)], [inf545])).
fof(inf543, plain, ~ p, inference(inf, [status(thm)], [inf544])).
fof(inf542, plain, ~ p, inference(inf, [status(thm)], [inf543])).
fof(inf541, plain, ~ p, inference(inf, [status(thm)], [inf542])).
fof(inf540, plain, ~ p, inference(inf, [status(thm)], [inf541])).
fof(inf539, plain, ~ p, inference(inf, [status(thm)], [inf540])).
fof(inf538, plain, ~ p, inference(inf, [status(thm)], [inf539])).
fof(inf537, plain, ~ p, inference(inf, [status(thm)], [inf538])).
fof(inf536, plain, ~ p, inference(inf, [status(thm)], [inf537])).
fof(inf535, plain, ~ p, inference(inf, [status(thm)], [inf536])).
fof(inf534, plain, ~ p, inference(inf, [status(thm)], [inf535])).
fof(inf533, plain, ~ p, inference(inf, [status(thm)], [inf534])).
fof(inf532, plain, ~ p, inference(inf, [status(thm)], [inf533])).
fof(inf531, plain, ~ p, inference(inf, [status(thm)], [inf532])).
fof(inf530, plain, ~ p, inference(inf, [status(thm)], [inf531])).
fof(inf529, plain, ~ p, inference(inf, [status(thm)], [inf530])).
fof(inf528, plain, ~ p, inference(inf, [status(thm)], [inf529])).
fof(inf527, plain, ~ p, inference(inf, [status(thm)], [inf528])).
fof(inf526, plain, ~ p, inference(inf, [status(thm)], [inf527])).
fof(inf525, plain, ~ p, inference(inf, [status(thm)], [inf526])).
fof(inf524, plain, ~ p, inference(inf, [status(thm)], [inf525])).
fof(inf523, plain, ~ p, inference(inf, [status(thm)], [inf524])).
fof(inf522, plain, ~ p, inference(inf, [status(thm)], [inf523])).
fof(inf521, plain, ~ p, inference(inf, [status(thm)], [inf522])).
fof(inf520, plain, ~ p, inference(inf, [status(thm)], [inf521])).
fof(inf519, plain, ~ p, inference(inf, [status(thm)], [inf520])).
fof(inf518, plain, ~ p, inference(inf, [status(thm)], [inf519])).
fof(inf517, plain, ~ p, inference(inf, [status(thm)], [inf518])).
fof(inf516, plain, ~ p, inference(inf, [status(thm)], [inf517])).
fof(inf515, plain, ~ p, inference(inf, [status(thm)], [inf516])).
fof(inf514, plain, ~ p, inference(inf, [status(thm)], [inf515])).
fof(inf513, plain, ~ p, inference(inf, [status(thm)], [inf514])).
fof(inf512, plain, ~ p, inference(inf, [status(thm)], [inf513])).
fof(inf511, plain, ~ p, inference(inf, [status(thm)], [inf512])).
fof(inf510, plain, ~ p, inference(inf, [status(thm)], [inf511])).
fof(inf509, plain, ~ p, inference(inf, [status(thm)], [inf510])).
fof(inf508, plain, ~ p, inference(inf, [status(thm)], [inf509])).
fof(inf507, plain, ~ p, inference(inf, [status(thm)], [inf508])).
fof(inf506, plain, ~ p, inference(inf, [status(thm)], [inf507])).
fof(inf505, plain, ~ p, inference(inf, [status(thm)], [inf506])).
fof(inf504, plain, ~ p, inference(inf, [status(thm)], [inf505])).
fof(inf503, plain, ~ p, inference(inf, [status(thm)], [inf504])).
fof(inf502, plain, ~ p, inference(inf, [status(thm)], [inf503])).
fof(inf501, plain, ~ p, inference(inf, [status(thm)], [inf502])).
fof(inf500, plain, ~ p, inference(inf, [status(thm)], [inf501])).
fof(inf499, plain, ~ p, inference(inf, [status(thm)], [inf500])).
fof(inf498, plain, ~ p, inference(inf, [status(thm)], [inf499])).
fof(inf497, plain, ~ p, inference(inf, [status(thm)], [inf498])).
fof(inf496, plain, ~ p, inference(inf, [status(thm)], [inf497])).
fof(inf495, plain, ~ p, inference(inf, [status(thm)], [inf496])).
fof(inf494, plain, ~ p, inference(inf, [status(thm)], [inf495])).
fof(inf493, plain, ~ p, inference(inf, [status(thm)], [inf494])).
fof(inf492, plain, ~ p, inference(inf, [status(thm)], [inf493])).
fof(inf491, plain, ~ p, inference(inf, [status(thm)], [inf492])).
fof(inf490, plain, ~ p, inference(inf, [status(thm)], [inf491])).
fof(inf489, plain, ~ p, inference(inf, [status(thm)], [inf490])).
fof(inf488, plain, ~ p, inference(inf, [status(thm)], [inf489])).
fof(inf487, plain, ~ p, inference(inf, [status(thm)], [inf488])).
fof(inf486, plain, ~ p, inference(inf, [status(thm)], [inf487])).
fof(inf485, plain, ~ p, inference(inf, [status(thm)], [inf486])).
fof(inf484, plain, ~ p, inference(inf, [status(thm)], [inf485])).
fof(inf483, plain, ~ p, inference(inf, [status(thm)], [inf484])).
fof(inf482, plain, ~ p, inference(inf, [status(thm)], [inf483])).
fof(inf481, plain, ~ p, inference(inf, [status(thm)], [inf482])).
fof(inf480, plain, ~ p, inference(inf, [status(thm)], [inf481])).
fof(inf479, plain, ~ p, inference(inf, [status(thm)], [inf480])).
fof(inf478, plain, ~ p, inference(inf, [status(thm)], [inf479])).
fof(inf477, plain, ~ p, inference(inf, [status(thm)], [inf478])).
fof(inf476, plain, ~ p, inference(inf, [status(thm)], [inf477])).
fof(inf475, plain, ~ p, inference(inf, [status(thm)], [inf476])).
fof(inf474, plain, ~ p, inference(inf, [status(thm)], [inf475])).
fof(inf473, plain, ~ p, inference(inf, [status(thm)], [inf474])).
fof(inf472, plain, ~ p, inference(inf, [status(thm)], [inf473])).
fof(inf471, plain, ~ p, inference(inf, [status(thm)], [inf472])).
fof(inf470, plain, ~ p, inference(inf, [status(thm)], [inf471])).
fof(inf469, plain, ~ p, inference(inf, [status(thm)], [inf470])).
fof(inf468, plain, ~ p, inference(inf, [status(thm)], [inf469])).
fof(inf467, plain, ~ p, inference(inf, [status(thm)], [inf468])).
fof(inf466, plain, ~ p, inference(inf, [status(thm)], [inf467])).
fof(inf465, plain, ~ p, inference(inf, [status(thm)], [inf466])).
fof(inf464, plain, ~ p, inference(inf, [status(thm)], [inf465])).
fof(inf463, plain, ~ p, inference(inf, [status(thm)], [inf464])).
fof(inf462, plain, ~ p, inference(inf, [status(thm)], [inf463])).
fof(inf461, plain, ~ p, inference(inf, [status(thm)], [inf462])).
fof(inf460, plain, ~ p, inference(inf, [status(thm)], [inf461])).
fof(inf459, plain, ~ p, inference(inf, [status(thm)], [inf460])).
fof(inf458, plain, ~ p, inference(inf, [status(thm)], [inf459])).
fof(inf457, plain, ~ p, inference(inf, [status(thm)], [inf458])).
fof(inf456, plain, ~ p, inference(inf, [status(thm)], [inf457])).
fof(inf455, plain, ~ p, inference(inf, [status(thm)], [inf456])).
fof(inf454, plain, ~ p, inference(inf, [status(thm)], [inf455])).
fof(inf453, plain, ~ p, inference(inf, [status(thm)], [inf454])).
fof(inf452, plain, ~ p, inference(inf, [status(thm)], [inf453])).
fof(inf451, plain, ~ p, inference(inf, [status(thm)], [inf452])).
fof(inf450, plain, ~ p, inference(inf, [status(thm)], [inf451])).
fof(inf449, plain, ~ p, inference(inf, [status(thm)], [inf450])).
fof(inf448, plain, ~ p, inference(inf, [status(thm)], [inf449])).
fof(inf447, plain, ~ p, inference(inf, [status(thm)], [inf448])).
fof(inf446, plain, ~ p, inference(inf, [status(thm)], [inf447])).
fof(inf445, plain, ~ p, inference(inf, [status(thm)], [inf446])).
fof(inf444, plain, ~ p, inference(inf, [status(thm)], [inf445])).
fof(inf443, plain, ~ p, inference(inf, [status(thm)], [inf444])).
fof(inf442, plain, ~ p, inference(inf, [status(thm)], [inf443])).
fof(inf441, plain, ~ p, inference(inf, [status(thm)], [inf442])).
fof(inf440, plain, ~ p, inference(inf, [status(thm)], [inf441])).
fof(inf439, plain, ~ p, inference(inf, [status(thm)], [inf440])).
fof(inf438, plain, ~ p, inference(inf, [status(thm)], [inf439])).
fof(inf437, plain, ~ p, inference(inf, [status(thm)], [inf438])).
fof(inf436, plain, ~ p, inference(inf, [status(thm)], [inf437])).
fof(inf435, plain, ~ p, inference(inf, [status(thm)], [inf436])).
fof(inf434, plain, ~ p, inference(inf, [status(thm)], [inf435])).
fof(inf433, plain, ~ p, inference(inf, [status(thm)], [inf434])).
fof(inf432, plain, ~ p, inference(inf, [status(thm)], [inf433])).
fof(inf431, plain, ~ p, inference(inf, [status(thm)], [inf432])).
fof(inf430, plain, ~ p, inference(inf, [status(thm)], [inf431])).
fof(inf429, plain, ~ p, inference(inf, [status(thm)], [inf430])).
fof(inf428, plain, ~ p, inference(inf, [status(thm)], [inf429])).
fof(inf427, plain, ~ p, inference(inf, [status(thm)], [inf428])).
fof(inf426, plain, ~ p, inference(inf, [status(thm)], [inf427])).
fof(inf425, plain, ~ p, inference(inf, [status(thm)], [inf426])).
fof(inf424, plain, ~ p, inference(inf, [status(thm)], [inf425])).
fof(inf423, plain, ~ p, inference(inf, [status(thm)], [inf424])).
fof(inf422, plain, ~ p, inference(inf, [status(thm)], [inf423])).
fof(inf421, plain, ~ p, inference(inf, [status(thm)], [inf422])).
fof(inf420, plain, ~ p, inference(inf, [status(thm)], [inf421])).
fof(inf419, plain, ~ p, inference(inf, [status(thm)], [inf420])).
fof(inf418, plain, ~ p, inference(inf, [status(thm)], [inf419])).
fof(inf417, plain, ~ p, inference(inf, [status(thm)], [inf418])).
fof(inf416, plain, ~ p, inference(inf, [status(thm)], [inf417])).
fof(inf415, plain, ~ p, inference(inf, [status(thm)], [inf416])).
fof(inf414, plain, ~ p, inference(inf, [status(thm)], [inf415])).
fof(inf413, plain, ~ p, inference(inf, [status(thm)], [inf414])).
fof(inf412, plain, ~ p, inference(inf, [status(thm)], [inf413])).
fof(inf411, plain, ~ p, inference(inf, [status(thm)], [inf412])).
fof(inf410, plain, ~ p, inference(inf, [status(thm)], [inf411])).
fof(inf409, plain, ~ p, inference(inf, [status(thm)], [inf410])).
fof(inf408, plain, ~ p, inference(inf, [status(thm)], [inf409])).
fof(inf407, plain, ~ p, inference(inf, [status(thm)], [inf408])).
fof(inf406, plain, ~ p, inference(inf, [status(thm)], [inf407])).
fof(inf405, plain, ~ p, inference(inf, [status(thm)], [inf406])).
fof(inf404, plain, ~ p, inference(inf, [status(thm)], [inf405])).
fof(inf403, plain, ~ p, inference(inf, [status(thm)], [inf404])).
fof(inf402, plain, ~ p, inference(inf, [status(thm)], [inf403])).
fof(inf401, plain, ~ p, inference(inf, [status(thm)], [inf402])).
fof(inf400, plain, ~ p, inference(inf, [status(thm)], [inf401])).
fof(inf399, plain, ~ p, inference(inf, [status(thm)], [inf400])).
fof(inf398, plain, ~ p, inference(inf, [status(thm)], [inf399])).
fof(inf397, plain, ~ p, inference(inf, [status(thm)], [inf398])).
fof(inf396, plain, ~ p, inference(inf, [status(thm)], [inf397])).
fof(inf395, plain, ~ p, inference(inf, [status(thm)], [inf396])).
fof(inf394, plain, ~ p, inference(inf, [status(thm)], [inf395])).
fof(inf393, plain, ~ p, inference(inf, [status(thm)], [inf394])).
fof(inf392, plain, ~ p, inference(inf, [status(thm)], [inf393])).
fof(inf391, plain, ~ p, inference(inf, [status(thm)], [inf392])).
fof(inf390, plain, ~ p, inference(inf, [status(thm)], [inf391])).
fof(inf389, plain, ~ p, inference(inf, [status(thm)], [inf390])).
fof(inf388, plain, ~ p, inference(inf, [status(thm)], [inf389])).
fof(inf387, plain, ~ p, inference(inf, [status(thm)], [inf388])).
fof(inf386, plain, ~ p, inference(inf, [status(thm)], [inf387])).
fof(inf385, plain, ~ p, inference(inf, [status(thm)], [inf386])).
fof(inf384, plain, ~ p, inference(inf, [status(thm)], [inf385])).
fof(inf383, plain, ~ p, inference(inf, [status(thm)], [inf384])).
fof(inf382, plain, ~ p, inference(inf, [status(thm)], [inf383])).
fof(inf381, plain, ~ p, inference(inf, [status(thm)], [inf382])).
fof(inf380, plain, ~ p, inference(inf, [status(thm)], [inf381])).
fof(inf379, plain, ~ p, inference(inf, [status(thm)], [inf380])).
fof(inf378, plain, ~ p, inference(inf, [status(thm)], [inf379])).
fof(inf377, plain, ~ p, inference(inf, [status(thm)], [inf378])).
fof(inf376, plain, ~ p, inference(inf, [status(thm)], [inf377])).
fof(inf375, plain, ~ p, inference(inf, [status(thm)], [inf376])).
fof(inf374, plain, ~ p, inference(inf, [status(thm)], [inf375])).
fof(inf373, plain, ~ p, inference(inf, [status(thm)], [inf374])).
fof(inf372, plain, ~ p, inference(inf, [status(thm)], [inf373])).
fof(inf371, plain, ~ p, inference(inf, [status(thm)], [inf372])).
fof(inf370, plain, ~ p, inference(inf, [status(thm)], [inf371])).
fof(inf369, plain, ~ p, inference(inf, [status(thm)], [inf370])).
fof(inf368, plain, ~ p, inference(inf, [status(thm)], [inf369])).
fof(inf367, plain, ~ p, inference(inf, [status(thm)], [inf368])).
fof(inf366, plain, ~ p, inference(inf, [status(thm)], [inf367])).
fof(inf365, plain, ~ p, inference(inf, [status(thm)], [inf366])).
fof(inf364, plain, ~ p, inference(inf, [status(thm)], [inf365])).
fof(inf363, plain, ~ p, inference(inf, [status(thm)], [inf364])).
fof(inf362, plain, ~ p, inference(inf, [status(thm)], [inf363])).
fof(inf361, plain, ~ p, inference(inf, [status(thm)], [inf362])).
fof(inf360, plain, ~ p, inference(inf, [status(thm)], [inf361])).
fof(inf359, plain, ~ p, inference(inf, [status(thm)], [inf360])).
fof(inf358, plain, ~ p, inference(inf, [status(thm)], [inf359])).
fof(inf357, plain, ~ p, inference(inf, [status(thm)], [inf358])).
fof(inf356, plain, ~ p, inference(inf, [status(thm)], [inf357])).
fof(inf355, plain, ~ p, inference(inf, [status(thm)], [inf356])).
fof(inf354, plain, ~ p, inference(inf, [status(thm)], [inf355])).
fof(inf353, plain, ~ p, inference(inf, [status(thm)], [inf354])).
fof(inf352, plain, ~ p, inference(inf, [status(thm)], [inf353])).
fof(inf351, plain, ~ p, inference(inf, [status(thm)], [inf352])).
fof(inf350, plain, ~ p, inference(inf, [status(thm)], [inf351])).
fof(inf349, plain, ~ p, inference(inf, [status(thm)], [inf350])).
fof(inf348, plain, ~ p, inference(inf, [status(thm)], [inf349])).
fof(inf347, plain, ~ p, inference(inf, [status(thm)], [inf348])).
fof(inf346, plain, ~ p, inference(inf, [status(thm)], [inf347])).
fof(inf345, plain, ~ p, inference(inf, [status(thm)], [inf346])).
fof(inf344, plain, ~ p, inference(inf, [status(thm)], [inf345])).
fof(inf343, plain, ~ p, inference(inf, [status(thm)], [inf344])).
fof(inf342, plain, ~ p, inference(inf, [status(thm)], [inf343])).
fof(inf341, plain, ~ p, inference(inf, [status(thm)], [inf342])).
fof(inf340, plain, ~ p, inference(inf, [status(thm)], [inf341])).
fof(inf339, plain, ~ p, inference(inf, [status(thm)], [inf340])).
fof(inf338, plain, ~ p, inference(inf, [status(thm)], [inf339])).
fof(inf337, plain, ~ p, inference(inf, [status(thm)], [inf338])).
fof(inf336, plain, ~ p, inference(inf, [status(thm)], [inf337])).
fof(inf335, plain, ~ p, inference(inf, [status(thm)], [inf336])).
fof(inf334, plain, ~ p, inference(inf, [status(thm)], [inf335])).
fof(inf333, plain, ~ p, inference(inf, [status(thm)], [inf334])).
fof(inf332, plain, ~ p, inference(inf, [status(thm)], [inf333])).
fof(inf331, plain, ~ p, inference(inf, [status(thm)], [inf332])).
fof(inf330, plain, ~ p, inference(inf, [status(thm)], [inf331])).
fof(inf329, plain, ~ p, inference(inf, [status(thm)], [inf330])).
fof(inf328, plain, ~ p, inference(inf, [status(thm)], [inf329])).
fof(inf327, plain, ~ p, inference(inf, [status(thm)], [inf328])).
fof(inf326, plain, ~ p, inference(inf, [status(thm)], [inf327])).
fof(inf325, plain, ~ p, inference(inf, [status(thm)], [inf326])).
fof(inf324, plain, ~ p, inference(inf, [status(thm)], [inf325])).
fof(inf323, plain, ~ p, inference(inf, [status(thm)], [inf324])).
fof(inf322, plain, ~ p, inference(inf, [status(thm)], [inf323])).
fof(inf321, plain, ~ p, inference(inf, [status(thm)], [inf322])).
fof(inf320, plain, ~ p, inference(inf, [status(thm)], [inf321])).
fof(inf319, plain, ~ p, inference(inf, [status(thm)], [inf320])).
fof(inf318, plain, ~ p, inference(inf, [status(thm)], [inf319])).
fof(inf317, plain, ~ p, inference(inf, [status(thm)], [inf318])).
fof(inf316, plain, ~ p, inference(inf, [status(thm)], [inf317])).
fof(inf315, plain, ~ p, inference(inf, [status(thm)], [inf316])).
fof(inf314, plain, ~ p, inference(inf, [status(thm)], [inf315])).
fof(inf313, plain, ~ p, inference(inf, [status(thm)], [inf314])).
fof(inf312, plain, ~ p, inference(inf, [status(thm)], [inf313])).
fof(inf311, plain, ~ p, inference(inf, [status(thm)], [inf312])).
fof(inf310, plain, ~ p, inference(inf, [status(thm)], [inf311])).
fof(inf309, plain, ~ p, inference(inf, [status(thm)], [inf310])).
fof(inf308, plain, ~ p, inference(inf, [status(thm)], [inf309])).
fof(inf307, plain, ~ p, inference(inf, [status(thm)], [inf308])).
fof(inf306, plain, ~ p, inference(inf, [status(thm)], [inf307])).
fof(inf305, plain, ~ p, inference(inf, [status(thm)], [inf306])).
fof(inf304, plain, ~ p, inference(inf, [status(thm)], [inf305])).
fof(inf303, plain, ~ p, inference(inf, [status(thm)], [inf304])).
fof(inf302, plain, ~ p, inference(inf, [status(thm)], [inf303])).
fof(inf301, plain, ~ p, inference(inf, [status(thm)], [inf302])).
fof(inf300, plain, ~ p, inference(inf, [status(thm)], [inf301])).
fof(inf299, plain, ~ p, inference(inf, [status(thm)], [inf300])).
fof(inf298, plain, ~ p, inference(inf, [status(thm)], [inf299])).
fof(inf297, plain, ~ p, inference(inf, [status(thm)], [inf298])).
fof(inf296, plain, ~ p, inference(inf, [status(thm)], [inf297])).
fof(inf295, plain, ~ p, inference(inf, [status(thm)], [inf296])).
fof(inf294, plain, ~ p, inference(inf, [status(thm)], [inf295])).
fof(inf293, plain, ~ p, inference(inf, [status(thm)], [inf294])).
fof(inf292, plain, ~ p, inference(inf, [status(thm)], [inf293])).
fof(inf291, plain, ~ p, inference(inf, [status(thm)], [inf292])).
fof(inf290, plain, ~ p, inference(inf, [status(thm)], [inf291])).
fof(inf289, plain, ~ p, inference(inf, [status(thm)], [inf290])).
fof(inf288, plain, ~ p, inference(inf, [status(thm)], [inf289])).
fof(inf287, plain, ~ p, inference(inf, [status(thm)], [inf288])).
fof(inf286, plain, ~ p, inference(inf, [status(thm)], [inf287])).
fof(inf285, plain, ~ p, inference(inf, [status(thm)], [inf286])).
fof(inf284, plain, ~ p, inference(inf, [status(thm)], [inf285])).
fof(inf283, plain, ~ p, inference(inf, [status(thm)], [inf284])).
fof(inf282, plain, ~ p, inference(inf, [status(thm)], [inf283])).
fof(inf281, plain, ~ p, inference(inf, [status(thm)], [inf282])).
fof(inf280, plain, ~ p, inference(inf, [status(thm)], [inf281])).
fof(inf279, plain, ~ p, inference(inf, [status(thm)], [inf280])).
fof(inf278, plain, ~ p, inference(inf, [status(thm)], [inf279])).
fof(inf277, plain, ~ p, inference(inf, [status(thm)], [inf278])).
fof(inf276, plain, ~ p, inference(inf, [status(thm)], [inf277])).
fof(inf275, plain, ~ p, inference(inf, [status(thm)], [inf276])).
fof(inf274, plain, ~ p, inference(inf, [status(thm)], [inf275])).
fof(inf273, plain, ~ p, inference(inf, [status(thm)], [inf274])).
fof(inf272, plain, ~ p, inference(inf, [status(thm)], [inf273])).
fof(inf271, plain, ~ p, inference(inf, [status(thm)], [inf272])).
fof(inf270, plain, ~ p, inference(inf, [status(thm)], [inf271])).
fof(inf269, plain, ~ p, inference(inf, [status(thm)], [inf270])).
fof(inf268, plain, ~ p, inference(inf, [status(thm)], [inf269])).
fof(inf267, plain, ~ p, inference(inf, [status(thm)], [inf268])).
fof(inf266, plain, ~ p, inference(inf, [status(thm)], [inf267])).
fof(inf265, plain, ~ p, inference(inf, [status(thm)], [inf266])).
fof(inf264, plain, ~ p, inference(inf, [status(thm)], [inf265])).
fof(inf263, plain, ~ p, inference(inf, [status(thm)], [inf264])).
fof(inf262, plain, ~ p, inference(inf, [status(thm)], [inf263])).
fof(inf261, plain, ~ p, inference(inf, [status(thm)], [inf262])).
fof(inf260, plain, ~ p, inference(inf, [status(thm)], [inf261])).
fof(inf259, plain, ~ p, inference(inf, [status(thm)], [inf260])).
fof(inf258, plain, ~ p, inference(inf, [status(thm)], [inf259])).
fof(inf257, plain, ~ p, inference(inf, [status(thm)], [inf258])).
fof(inf256, plain, ~ p, inference(inf, [status(thm)], [inf257])).
fof(inf255, plain, ~ p, inference(inf, [status(thm)], [inf256])).
fof(inf254, plain, ~ p, inference(inf, [status(thm)], [inf255])).
fof(inf253, plain, ~ p, inference(inf, [status(thm)], [inf254])).
fof(inf252, plain, ~ p, inference(inf, [status(thm)], [inf253])).
fof(inf251, plain, ~ p, inference(inf, [status(thm)], [inf252])).
fof(inf250, plain, ~ p, inference(inf, [status(thm)], [inf251])).
fof(inf249, plain, ~ p, inference(inf, [status(thm)], [inf250])).
fof(inf248, plain, ~ p, inference(inf, [status(thm)], [inf249])).
fof(inf247, plain, ~ p, inference(inf, [status(thm)], [inf248])).
fof(inf246, plain, ~ p, inference(inf, [status(thm)], [inf247])).
fof(inf245, plain, ~ p, inference(inf, [status(thm)], [inf246])).
fof(inf244, plain, ~ p, inference(inf, [status(thm)], [inf245])).
fof(inf243, plain, ~ p, inference(inf, [status(thm)], [inf244])).
fof(inf242, plain, ~ p, inference(inf, [status(thm)], [inf243])).
fof(inf241, plain, ~ p, inference(inf, [status(thm)], [inf242])).
fof(inf240, plain, ~ p, inference(inf, [status(thm)], [inf241])).
fof(inf239, plain, ~ p, inference(inf, [status(thm)], [inf240])).
fof(inf238, plain, ~ p, inference(inf, [status(thm)], [inf239])).
fof(inf237, plain, ~ p, inference(inf, [status(thm)], [inf238])).
fof(inf236, plain, ~ p, inference(inf, [status(thm)], [inf237])).
fof(inf235, plain, ~ p, inference(inf, [status(thm)], [inf236])).
fof(inf234, plain, ~ p, inference(inf, [status(thm)], [inf235])).
fof(inf233, plain, ~ p, inference(inf, [status(thm)], [inf234])).
fof(inf232, plain, ~ p, inference(inf, [status(thm)], [inf233])).
fof(inf231, plain, ~ p, inference(inf, [status(thm)], [inf232])).
fof(inf230, plain, ~ p, inference(inf, [status(thm)], [inf231])).
fof(inf229, plain, ~ p, inference(inf, [status(thm)], [inf230])).
fof(inf228, plain, ~ p, inference(inf, [status(thm)], [inf229])).
fof(inf227, plain, ~ p, inference(inf, [status(thm)], [inf228])).
fof(inf226, plain, ~ p, inference(inf, [status(thm)], [inf227])).
fof(inf225, plain, ~ p, inference(inf, [status(thm)], [inf226])).
fof(inf224, plain, ~ p, inference(inf, [status(thm)], [inf225])).
fof(inf223, plain, ~ p, inference(inf, [status(thm)], [inf224])).
fof(inf222, plain, ~ p, inference(inf, [status(thm)], [inf223])).
fof(inf221, plain, ~ p, inference(inf, [status(thm)], [inf222])).
fof(inf220, plain, ~ p, inference(inf, [status(thm)], [inf221])).
fof(inf219, plain, ~ p, inference(inf, [status(thm)], [inf220])).
fof(inf218, plain, ~ p, inference(inf, [status(thm)], [inf219])).
fof(inf217, plain, ~ p, inference(inf, [status(thm)], [inf218])).
fof(inf216, plain, ~ p, inference(inf, [status(thm)], [inf217])).
fof(inf215, plain, ~ p, inference(inf, [status(thm)], [inf216])).
fof(inf214, plain, ~ p, inference(inf, [status(thm)], [inf215])).
fof(inf213, plain, ~ p, inference(inf, [status(thm)], [inf214])).
fof(inf212, plain, ~ p, inference(inf, [status(thm)], [inf213])).
fof(inf211, plain, ~ p, inference(inf, [status(thm)], [inf212])).
fof(inf210, plain, ~ p, inference(inf, [status(thm)], [inf211])).
fof(inf209, plain, ~ p, inference(inf, [status(thm)], [inf210])).
fof(inf208, plain, ~ p, inference(inf, [status(thm)], [inf209])).
fof(inf207, plain, ~ p, inference(inf, [status(thm)], [inf208])).
fof(inf206, plain, ~ p, inference(inf, [status(thm)], [inf207])).
fof(inf205, plain, ~ p, inference(inf, [status(thm)], [inf206])).
fof(inf204, plain, ~ p, inference(inf, [status(thm)], [inf205])).
fof(inf203, plain, ~ p, inference(inf, [status(thm)], [inf204])).
fof(inf202, plain, ~ p, inference(inf, [status(thm)], [inf203])).
fof(inf201, plain, ~ p, inference(inf, [status(thm)], [inf202])).
fof(inf200, plain, ~ p, inference(inf, [status(thm)], [inf201])).
fof(inf199, plain, ~ p, inference(inf, [status(thm)], [inf200])).
fof(inf198, plain, ~ p, inference(inf, [status(thm)], [inf199])).
fof(inf197, plain, ~ p, inference(inf, [status(thm)], [inf198])).
fof(inf196, plain, ~ p, inference(inf, [status(thm)], [inf197])).
fof(inf195, plain, ~ p, inference(inf, [status(thm)], [inf196])).
fof(inf194, plain, ~ p, inference(inf, [status(thm)], [inf195])).
fof(inf193, plain, ~ p, inference(inf, [status(thm)], [inf194])).
fof(inf192, plain, ~ p, inference(inf, [status(thm)], [inf193])).
fof(inf191, plain, ~ p, inference(inf, [status(thm)], [inf192])).
fof(inf190, plain, ~ p, inference(inf, [status(thm)], [inf191])).
fof(inf189, plain, ~ p, inference(inf, [status(thm)], [inf190])).
fof(inf188, plain, ~ p, inference(inf, [status(thm)], [inf189])).
fof(inf187, plain, ~ p, inference(inf, [status(thm)], [inf188])).
fof(inf186, plain, ~ p, inference(inf, [status(thm)], [inf187])).
fof(inf185, plain, ~ p, inference(inf, [status(thm)], [inf186])).
fof(inf184, plain, ~ p, inference(inf, [status(thm)], [inf185])).
fof(inf183, plain, ~ p, inference(inf, [status(thm)], [inf184])).
fof(inf182, plain, ~ p, inference(inf, [status(thm)], [inf183])).
fof(inf181, plain, ~ p, inference(inf, [status(thm)], [inf182])).
fof(inf180, plain, ~ p, inference(inf, [status(thm)], [inf181])).
fof(inf179, plain, ~ p, inference(inf, [status(thm)], [inf180])).
fof(inf178, plain, ~ p, inference(inf, [status(thm)], [inf179])).
fof(inf177, plain, ~ p, inference(inf, [status(thm)], [inf178])).
fof(inf176, plain, ~ p, inference(inf, [status(thm)], [inf177])).
fof(inf175, plain, ~ p, inference(inf, [status(thm)], [inf176])).
fof(inf174, plain, ~ p, inference(inf, [status(thm)], [inf175])).
fof(inf173, plain, ~ p, inference(inf, [status(thm)], [inf174])).
fof(inf172, plain, ~ p, inference(inf, [status(thm)], [inf173])).
fof(inf171, plain, ~ p, inference(inf, [status(thm)], [inf172])).
fof(inf170, plain, ~ p, inference(inf, [status(thm)], [inf171])).
fof(inf169, plain, ~ p, inference(inf, [status(thm)], [inf170])).
fof(inf168, plain, ~ p, inference(inf, [status(thm)], [inf169])).
fof(inf167, plain, ~ p, inference(inf, [status(thm)], [inf168])).
fof(inf166, plain, ~ p, inference(inf, [status(thm)], [inf167])).
fof(inf165, plain, ~ p, inference(inf, [status(thm)], [inf166])).
fof(inf164, plain, ~ p, inference(inf, [status(thm)], [inf165])).
fof(inf163, plain, ~ p, inference(inf, [status(thm)], [inf164])).
fof(inf162, plain, ~ p, inference(inf, [status(thm)], [inf163])).
fof(inf161, plain, ~ p, inference(inf, [status(thm)], [inf162])).
fof(inf160, plain, ~ p, inference(inf, [status(thm)], [inf161])).
fof(inf159, plain, ~ p, inference(inf, [status(thm)], [inf160])).
fof(inf158, plain, ~ p, inference(inf, [status(thm)], [inf159])).
fof(inf157, plain, ~ p, inference(inf, [status(thm)], [inf158])).
fof(inf156, plain, ~ p, inference(inf, [status(thm)], [inf157])).
fof(inf155, plain, ~ p, inference(inf, [status(thm)], [inf156])).
fof(inf154, plain, ~ p, inference(inf, [status(thm)], [inf155])).
fof(inf153, plain, ~ p, inference(inf, [status(thm)], [inf154])).
fof(inf152, plain, ~ p, inference(inf, [status(thm)], [inf153])).
fof(inf151, plain, ~ p, inference(inf, [status(thm)], [inf152])).
fof(inf150, plain, ~ p, inference(inf, [status(thm)], [inf151])).
fof(inf149, plain, ~ p, inference(inf, [status(thm)], [inf150])).
fof(inf148, plain, ~ p, inference(inf, [status(thm)], [inf149])).
fof(inf147, plain, ~ p, inference(inf, [status(thm)], [inf148])).
fof(inf146, plain, ~ p, inference(inf, [status(thm)], [inf147])).
fof(inf145, plain, ~ p, inference(inf, [status(thm)], [inf146])).
fof(inf144, plain, ~ p, inference(inf, [status(thm)], [inf145])).
fof(inf143, plain, ~ p, inference(inf, [status(thm)], [inf144])).
fof(inf142, plain, ~ p, inference(inf, [status(thm)], [inf143])).
fof(inf141, plain, ~ p, inference(inf, [status(thm)], [inf142])).
fof(inf140, plain, ~ p, inference(inf, [status(thm)], [inf141])).
fof(inf139, plain, ~ p, inference(inf, [status(thm)], [inf140])).
fof(inf138, plain, ~ p, inference(inf, [status(thm)], [inf139])).
fof(inf137, plain, ~ p, inference(inf, [status(thm)], [inf138])).
fof(inf136, plain, ~ p, inference(inf, [status(thm)], [inf137])).
fof(inf135, plain, ~ p, inference(inf, [status(thm)], [inf136])).
fof(inf134, plain, ~ p, inference(inf, [status(thm)], [inf135])).
fof(inf133, plain, ~ p, inference(inf, [status(thm)], [inf134])).
fof(inf132, plain, ~ p, inference(inf, [status(thm)], [inf133])).
fof(inf131, plain, ~ p, inference(inf, [status(thm)], [inf132])).
fof(inf130, plain, ~ p, inference(inf, [status(thm)], [inf131])).
fof(inf129, plain, ~ p, inference(inf, [status(thm)], [inf130])).
fof(inf128, plain, ~ p, inference(inf, [status(thm)], [inf129])).
fof(inf127, plain, ~ p, inference(inf, [status(thm)], [inf128])).
fof(inf126, plain, ~ p, inference(inf, [status(thm)], [inf127])).
fof(inf125, plain, ~ p, inference(inf, [status(thm)], [inf126])).
fof(inf124, plain, ~ p, inference(inf, [status(thm)], [inf125])).
fof(inf123, plain, ~ p, inference(inf, [status(thm)], [inf124])).
fof(inf122, plain, ~ p, inference(inf, [status(thm)], [inf123])).
fof(inf121, plain, ~ p, inference(inf, [status(thm)], [inf122])).
fof(inf120, plain, ~ p, inference(inf, [status(thm)], [inf121])).
fof(inf119, plain, ~ p, inference(inf, [status(thm)], [inf120])).
fof(inf118, plain, ~ p, inference(inf, [status(thm)], [inf119])).
fof(inf117, plain, ~ p, inference(inf, [status(thm)], [inf118])).
fof(inf116, plain, ~ p, inference(inf, [status(thm)], [inf117])).
fof(inf115, plain, ~ p, inference(inf, [status(thm)], [inf116])).
fof(inf114, plain, ~ p, inference(inf, [status(thm)], [inf115])).
fof(inf113, plain, ~ p, inference(inf, [status(thm)], [inf114])).
fof(inf112, plain, ~ p, inference(inf, [status(thm)], [inf113])).
fof(inf111, plain, ~ p, inference(inf, [status(thm)], [inf112])).
fof(inf110, plain, ~ p, inference(inf, [status(thm)], [inf111])).
fof(inf109, plain, ~ p, inference(inf, [status(thm)], [inf110])).
fof(inf108, plain, ~ p, inference(inf, [status(thm)], [inf109])).
fof(inf107, plain, ~ p, inference(inf, [status(thm)], [inf108])).
fof(inf106, plain, ~ p, inference(inf, [status(thm)], [inf107])).
fof(inf105, plain, ~ p, inference(inf, [status(thm)], [inf106])).
fof(inf104, plain, ~ p, inference(inf, [status(thm)], [inf105])).
fof(inf103, plain, ~ p, inference(inf, [status(thm)], [inf104])).
fof(inf102, plain, ~ p, inference(inf, [status(thm)], [inf103])).
fof(inf101, plain, ~ p, inference(inf, [status(thm)], [inf102])).
fof(inf100, plain, ~ p, inference(inf, [status(thm)], [inf101])).
fof(inf99, plain, ~ p, inference(inf, [status(thm)], [inf100])).
fof(inf98, plain, ~ p, inference(inf, [status(thm)], [inf99])).
fof(inf97, plain, ~ p, inference(inf, [status(thm)], [inf98])).
fof(inf96, plain, ~ p, inference(inf, [status(thm)], [inf97])).
fof(inf95, plain, ~ p, inference(inf, [status(thm)], [inf96])).
fof(inf94, plain, ~ p, inference(inf, [status(thm)], [inf95])).
fof(inf93, plain, ~ p, inference(inf, [status(thm)], [inf94])).
fof(inf92, plain, ~ p, inference(inf, [status(thm)], [inf93])).
fof(inf91, plain, ~ p, inference(inf, [status(thm)], [inf92])).
fof(inf90, plain, ~ p, inference(inf, [status(thm)], [inf91])).
fof(inf89, plain, ~ p, inference(inf, [status(thm)], [inf90])).
fof(inf88, plain, ~ p, inference(inf, [status(thm)], [inf89])).
fof(inf87, plain, ~ p, inference(inf, [status(thm)], [inf88])).
fof(inf86, plain, ~ p, inference(inf, [status(thm)], [inf87])).
fof(inf85, plain, ~ p, inference(inf, [status(thm)], [inf86])).
fof(inf84, plain, ~ p, inference(inf, [status(thm)], [inf85])).
fof(inf83, plain, ~ p, inference(inf, [status(thm)], [inf84])).
fof(inf82, plain, ~ p, inference(inf, [status(thm)], [inf83])).
fof(inf81, plain, ~ p, inference(inf, [status(thm)], [inf82])).
fof(inf80, plain, ~ p, inference(inf, [status(thm)], [inf81])).
fof(inf79, plain, ~ p, inference(inf, [status(thm)], [inf80])).
fof(inf78, plain, ~ p, inference(inf, [status(thm)], [inf79])).
fof(inf77, plain, ~ p, inference(inf, [status(thm)], [inf78])).
fof(inf76, plain, ~ p, inference(inf, [status(thm)], [inf77])).
fof(inf75, plain, ~ p, inference(inf, [status(thm)], [inf76])).
fof(inf74, plain, ~ p, inference(inf, [status(thm)], [inf75])).
fof(inf73, plain, ~ p, inference(inf, [status(thm)], [inf74])).
fof(inf72, plain, ~ p, inference(inf, [status(thm)], [inf73])).
fof(inf71, plain, ~ p, inference(inf, [status(thm)], [inf72])).
fof(inf70, plain, ~ p, inference(inf, [status(thm)], [inf71])).
fof(inf69, plain, ~ p, inference(inf, [status(thm)], [inf70])).
fof(inf68, plain, ~ p, inference(inf, [status(thm)], [inf69])).
fof(inf67, plain, ~ p, inference(inf, [status(thm)], [inf68])).
fof(inf66, plain, ~ p, inference(inf, [status(thm)], [inf67])).
fof(inf65, plain, ~ p, inference(inf, [status(thm)], [inf66])).
fof(inf64, plain, ~ p, inference(inf, [status(thm)], [inf65])).
fof(inf63, plain, ~ p, inference(inf, [status(thm)], [inf64])).
fof(inf62, plain, ~ p, inference(inf, [status(thm)], [inf63])).
fof(inf61, plain, ~ p, inference(inf, [status(thm)], [inf62])).
fof(inf60, plain, ~ p, inference(inf, [status(thm)], [inf61])).
fof(inf59, plain, ~ p, inference(inf, [status(thm)], [inf60])).
fof(inf58, plain, ~ p, inference(inf, [status(thm)], [inf59])).
fof(inf57, plain, ~ p, inference(inf, [status(thm)], [inf58])).
fof(inf56, plain, ~ p, inference(inf, [status(thm)], [inf57])).
fof(inf55, plain, ~ p, inference(inf, [status(thm)], [inf56])).
fof(inf54, plain, ~ p, inference(inf, [status(thm)], [inf55])).
fof(inf53, plain, ~ p, inference(inf, [status(thm)], [inf54])).
fof(inf52, plain, ~ p, inference(inf, [status(thm)], [inf53])).
fof(inf51, plain, ~ p, inference(inf, [status(thm)], [inf52])).
fof(inf50, plain, ~ p, inference(inf, [status(thm)], [inf51])).
fof(inf49, plain, ~ p, inference(inf, [status(thm)], [inf50])).
fof(inf48, plain, ~ p, inference(inf, [status(thm)], [inf49])).
fof(inf47, plain, ~ p, inference(inf, [status(thm)], [inf48])).
fof(inf46, plain, ~ p, inference(inf, [status(thm)], [inf47])).
fof(inf45, plain, ~ p, inference(inf, [status(thm)], [inf46])).
fof(inf44, plain, ~ p, inference(inf, [status(thm)], [inf45])).
fof(inf43, plain, ~ p, inference(inf, [status(thm)], [inf44])).
fof(inf42, plain, ~ p, inference(inf, [status(thm)], [inf43])).
fof(inf41, plain, ~ p, inference(inf, [status(thm)], [inf42])).
fof(inf40, plain, ~ p, inference(inf, [status(thm)], [inf41])).
fof(inf39, plain, ~ p, inference(inf, [status(thm)], [inf40])).
fof(inf38, plain, ~ p, inference(inf, [status(thm)], [inf39])).
fof(inf37, plain, ~ p, inference(inf, [status(thm)], [inf38])).
fof(inf36, plain, ~ p, inference(inf, [status(thm)], [inf37])).
fof(inf35, plain, ~ p, inference(inf, [status(thm)], [inf36])).
fof(inf34, plain, ~ p, inference(inf, [status(thm)], [inf35])).
fof(inf33, plain, ~ p, inference(inf, [status(thm)], [inf34])).
fof(inf32, plain, ~ p, inference(inf, [status(thm)], [inf33])).
fof(inf31, plain, ~ p, inference(inf, [status(thm)], [inf32])).
fof(inf30, plain, ~ p, inference(inf, [status(thm)], [inf31])).
fof(inf29, plain, ~ p, inference(inf, [status(thm)], [inf30])).
fof(inf28, plain, ~ p, inference(inf, [status(thm)], [inf29])).
fof(inf27, plain, ~ p, inference(inf, [status(thm)], [inf28])).
fof(inf26, plain, ~ p, inference(inf, [status(thm)], [inf27])).
fof(inf25, plain, ~ p, inference(inf, [status(thm)], [inf26])).
fof(inf24, plain, ~ p, inference(inf, [status(thm)], [inf25])).
fof(inf23, plain, ~ p, inference(inf, [status(thm)], [inf24])).
fof(inf22, plain, ~ p, inference(inf, [status(thm)], [inf23])).
fof(inf21, plain, ~ p, inference(inf, [status(thm)], [inf22])).
fof(inf20, plain, ~ p, inference(inf, [status(thm)], [inf21])).
fof(inf19, plain, ~ p, inference(inf, [status(thm)], [inf20])).
fof(inf18, plain, ~ p, inference(inf, [status(thm)], [inf19])).
fof(inf17, plain, ~ p, inference(inf, [status(thm)], [inf18])).
fof(inf16, plain, ~ p, inference(inf, [status(thm)], [inf17])).
fof(inf15, plain, ~ p, inference(inf, [status(thm)], [inf16])).
fof(inf14, plain, ~ p, inference(inf, [status(thm)], [inf15])).
fof(inf13, plain, ~ p, inference(inf, [status(thm)], [inf14])).
fof(inf12, plain, ~ p, inference(inf, [status(thm)], [inf13])).
fof(inf11, plain, ~ p, inference(inf, [status(thm)], [inf12])).
fof(inf10, plain, ~ p, inference(inf, [status(thm)], [inf11])).
fof(inf9, plain, ~ p, inference(inf, [status(thm)], [inf10])).
fof(inf8, plain, ~ p, inference(inf, [status(thm)], [inf9])).
fof(inf7, plain, ~ p, inference(inf, [status(thm)], [inf8])).
fof(inf6, plain, ~ p, inference(inf, [status(thm)], [inf7])).
fof(inf5, plain, ~ p, inference(inf, [status(thm)], [inf6])).
fof(inf4, plain, ~ p, inference(inf, [status(thm)], [inf5])).
fof(inf3, plain, ~ p, inference(inf, [status(thm)], [inf4])).
fof(inf2, plain, ~ p, inference(inf, [status(thm)], [inf3])).
fof(inf1, plain, ~ p, inference(inf, [status(thm)], [inf2])).
fof(refute, plain, $false, inference(inf, [status(thm)], [inf1, a])).
