% Detected formulas, will run a generic FOF schedule.
% WARNING Broken Constraint: if avatar_literal_polarity_advice(true) has been set then avatar(off) is equal to on
% lrs+1011_32_sil=2000:tgt=full:alpa=true:random_seed=2940223294:st=5:i=107:sd=1:av=off:ss=included:er=filter_2999 on SCT157+1 for (2999ds/107Mi)
% Instruction limit reached! 
% ------------------------------
% Version: Vampire 5.0.1 (Release build, commit 3f1362b99 on 2026-07-01 15:21:00 +0200)
% Linked with Z3 4.14.0.0 3c47fd96cf5645d0c42b2c819d9e9a84380aa721 z3-4.8.4-9178-g3c47fd96c
% CaDiCaL version: 2.1.3
% Termination reason: Instruction limit
% Termination phase: Saturation
% Time elapsed: 0.013 s
% Peak memory usage: 12 MB
% Instructions burned: 109 (million)
% lrs+10_2:3_to=lpo:sil=16000:sp=arity:random_seed=94428017:i=114:bd=all:av=off:ss=axioms:sgt=4_2999 on SCT157+1 for (2999ds/114Mi)
%  found proof, printing to "/tmp/vampire-proof-1513652-1513656"...
% ...printing done.
% Refutation found. Thanks to Tanya!
% SZS status Theorem for SCT157+1
% SZS output start Proof for SCT157+1
fof(f4,axiom,(
  v_a____ != v_b____),
  file('Problems/SCT/SCT157+1.p',fact_A_I1_J)).
fof(f5,axiom,(
  v_a_H____ != v_b_H____),
  file('Problems/SCT/SCT157+1.p',fact_A_I2_J)).
fof(f6,axiom,(
  v_a____ != v_b_H____ & v_b____ = v_a_H____),
  file('Problems/SCT/SCT157+1.p',fact__096a_A_126_061_Ab_H_A_G_Ab_A_061_Aa_H_096)).
fof(f7,axiom,(
  ! [X0] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_P____,X0)) <=> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,X0)))),
  file('Problems/SCT/SCT157+1.p',fact_A_I5_J)).
fof(f10,axiom,(
  c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf)),
  file('Problems/SCT/SCT157+1.p',fact_A_I3_J)).
fof(f11,axiom,(
  c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf)),
  file('Problems/SCT/SCT157+1.p',fact_A_I4_J)).
fof(f17,axiom,(
  ! [X0,X1,X2,X3,X4] : (X4 != X3 => (X3 != X2 => (X4 != X2 => (c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) => (c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X0,c_Arrow__Order__Mirabelle_OProf) => (! [X5] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,X5)) <=> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,X5))) => (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)) <=> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0)))))))))),
  file('Problems/SCT/SCT157+1.p',fact__C4_C)).
fof(f529,conjecture,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_F,v_P____)) <=> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____))),
  file('Problems/SCT/SCT157+1.p',conj_0)).
fof(f530,negated_conjecture,(
  ~(c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_F,v_P____)) <=> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)))),
  inference(negated_conjecture,[status(cth)],[f529])).
fof(f531,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_F,v_P____)) <~> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____))),
  inference(ennf_transformation,[status(thm)],[f530])).
fof(f539,plain,(
  ! [X0,X1,X2,X3,X4] : (((((((c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)) <=> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0))) | ? [X5] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,X5)) <~> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,X5)))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X0,c_Arrow__Order__Mirabelle_OProf)) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf)) | X2 = X4) | X2 = X3) | X3 = X4)),
  inference(ennf_transformation,[status(thm)],[f17])).
fof(f540,plain,(
  ! [X0,X1,X2,X3,X4] : ((c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)) <=> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0))) | ? [X5] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,X5)) <~> c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,X5))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X0,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | X2 = X4 | X2 = X3 | X3 = X4)),
  inference(flattening,[status(thm)],[f539])).
fof(f552,plain,(
  (~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_F,v_P____))) & (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_F,v_P____)))),
  inference(nnf_transformation,[status(thm)],[f531])).
fof(f560,plain,(
  ! [X0,X1,X2,X3,X4] : (((c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0))) & (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)))) | ? [X5] : ((~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,X5)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,X5))) & (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,X5)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,X5)))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X0,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | X2 = X4 | X2 = X3 | X3 = X4)),
  inference(nnf_transformation,[status(thm)],[f540])).
fof(f561,plain,(
  ! [X0,X1,X2,X3,X4] : (((c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0))) & (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)))) | ((~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,sK4(X0,X1,X2,X3,X4))) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,sK4(X0,X1,X2,X3,X4)))) & (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,sK4(X0,X1,X2,X3,X4))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,sK4(X0,X1,X2,X3,X4))))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X0,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | X2 = X4 | X2 = X3 | X3 = X4)),
  inference(skolemize,[status(esa),new_symbols(skolem,[sK4]),skolemize(X5,sK4(X0,X1,X2,X3,X4))],[f560])).
fof(f568,plain,(
  ! [X0] : ((c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_P____,X0)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,X0))) & (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,X0)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_P____,X0))))),
  inference(nnf_transformation,[status(thm)],[f7])).
fof(f569,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_F,v_P____))),
  inference(cnf_transformation,[status(thm)],[f552])).
fof(f570,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_F,v_P____))),
  inference(cnf_transformation,[status(thm)],[f552])).
fof(f582,plain,(
  ( ! [X2,X3,X0,X1,X4] : (~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,sK4(X0,X1,X2,X3,X4))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,sK4(X0,X1,X2,X3,X4))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X0,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | X2 = X4 | X2 = X3 | X3 = X4) )),
  inference(cnf_transformation,[status(thm)],[f561])).
fof(f583,plain,(
  ( ! [X2,X3,X0,X1,X4] : (~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,sK4(X0,X1,X2,X3,X4))) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,sK4(X0,X1,X2,X3,X4))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0)) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X0,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | X2 = X4 | X2 = X3 | X3 = X4) )),
  inference(cnf_transformation,[status(thm)],[f561])).
fof(f584,plain,(
  ( ! [X2,X3,X0,X1,X4] : (~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,sK4(X0,X1,X2,X3,X4))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,sK4(X0,X1,X2,X3,X4))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X0,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | X2 = X4 | X2 = X3 | X3 = X4) )),
  inference(cnf_transformation,[status(thm)],[f561])).
fof(f585,plain,(
  ( ! [X2,X3,X0,X1,X4] : (~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(X1,sK4(X0,X1,X2,X3,X4))) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(v_F,X0)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X3,X2),hAPP(X0,sK4(X0,X1,X2,X3,X4))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X4,X3),hAPP(v_F,X1)) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X0,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | X2 = X4 | X2 = X3 | X3 = X4) )),
  inference(cnf_transformation,[status(thm)],[f561])).
fof(f586,plain,(
  v_b____ = v_a_H____),
  inference(cnf_transformation,[status(thm)],[f6])).
fof(f587,plain,(
  v_a____ != v_b_H____),
  inference(cnf_transformation,[status(thm)],[f6])).
fof(f588,plain,(
  v_a____ != v_b____),
  inference(cnf_transformation,[status(thm)],[f4])).
fof(f598,plain,(
  v_a_H____ != v_b_H____),
  inference(cnf_transformation,[status(thm)],[f5])).
fof(f604,plain,(
  c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf)),
  inference(cnf_transformation,[status(thm)],[f10])).
fof(f609,plain,(
  ( ! [X0] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,X0)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_P____,X0))) )),
  inference(cnf_transformation,[status(thm)],[f568])).
fof(f610,plain,(
  ( ! [X0] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_b____),hAPP(v_P____,X0)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,X0))) )),
  inference(cnf_transformation,[status(thm)],[f568])).
fof(f611,plain,(
  c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf)),
  inference(cnf_transformation,[status(thm)],[f11])).
fof(f612,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))),
  inference(definition_unfolding,[status(thm)],[f570,f586])).
fof(f613,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))),
  inference(definition_unfolding,[status(thm)],[f569,f586])).
fof(f614,plain,(
  v_a____ != v_a_H____),
  inference(definition_unfolding,[status(thm)],[f588,f586])).
fof(f619,plain,(
  ( ! [X0] : (~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,X0)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,X0))) )),
  inference(definition_unfolding,[status(thm)],[f610,f586])).
fof(f620,plain,(
  ( ! [X0] : (~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,X0)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,X0))) )),
  inference(definition_unfolding,[status(thm)],[f609,f586])).
fof(f658,plain,(
  ( ! [X0,X1] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(v_F,X1)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,X1,v_b_H____,v_a_H____,X0))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(X1,sK4(v_P_H____,X1,v_b_H____,v_a_H____,X0))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | v_b_H____ = X0 | v_a_H____ = v_b_H____ | v_a_H____ = X0 | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))) )),
  inference(resolution,[status(thm)],[f584,f613])).
fof(f659,plain,(
  ( ! [X0,X1] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(v_F,X1)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,X1,v_b_H____,v_a_H____,X0))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(X1,sK4(v_P_H____,X1,v_b_H____,v_a_H____,X0))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | v_b_H____ = X0 | v_a_H____ = v_b_H____ | v_a_H____ = X0 | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))) )),
  inference(forward_subsumption_resolution,[status(thm)],[f658,f611])).
fof(f660,plain,(
  ( ! [X0,X1] : (~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,X1,v_b_H____,v_a_H____,X0))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(X1,sK4(v_P_H____,X1,v_b_H____,v_a_H____,X0))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(v_F,X1)) | v_b_H____ = X0 | v_a_H____ = X0 | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))) )),
  inference(forward_subsumption_resolution,[status(thm)],[f659,f598])).
fof(f661,plain,(
  ( ! [X0] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,X0))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,X0))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(v_F,v_P____)) | v_b_H____ = X0 | v_a_H____ = X0 | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))) )),
  inference(resolution,[status(thm)],[f660,f604])).
fof(f663,plain,(
  ( ! [X0] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,X0))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,X0))) | v_b_H____ = X0 | v_a_H____ = X0 | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,X0,v_a_H____),hAPP(v_F,v_P____))) )),
  inference(resolution,[status(thm)],[f661,f619])).
fof(f679,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | v_a____ = v_b_H____ | v_a____ = v_a_H____ | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))),
  inference(factoring,[status(thm)],[f663])).
fof(f680,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | v_a____ = v_b_H____ | v_a____ = v_a_H____ | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))),
  inference(duplicate_literal_removal,[status(thm)],[f679])).
fof(f683,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | v_a____ = v_a_H____ | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))),
  inference(forward_subsumption_resolution,[status(thm)],[f680,f587])).
fof(f685,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))),
  inference(forward_subsumption_resolution,[status(thm)],[f683,f614])).
fof(f686,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))),
  inference(resolution,[status(thm)],[f685,f620])).
fof(f687,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____)) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(resolution,[status(thm)],[f685,f585])).
fof(f689,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(duplicate_literal_removal,[status(thm)],[f687])).
fof(f690,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f689,f612])).
fof(f691,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f690,f611])).
fof(f692,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f691,f604])).
fof(f693,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f692,f587])).
fof(f694,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f693,f598])).
fof(f695,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____))),
  inference(forward_subsumption_resolution,[status(thm)],[f694,f614])).
fof(f700,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))),
  inference(resolution,[status(thm)],[f695,f686])).
fof(f704,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____))),
  inference(forward_subsumption_resolution,[status(thm)],[f700,f612])).
fof(f706,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____))),
  inference(resolution,[status(thm)],[f704,f613])).
fof(f713,plain,(
  ( ! [X0,X1] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,X0),hAPP(v_F,X1)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,X0),hAPP(X1,sK4(X1,v_P____,X0,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(X1,v_P____,X0,v_a_H____,v_a____))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = X0 | v_a_H____ = X0 | v_a____ = v_a_H____) )),
  inference(resolution,[status(thm)],[f706,f582])).
fof(f716,plain,(
  ( ! [X0,X1] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,X0),hAPP(v_F,X1)) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,X0),hAPP(X1,sK4(X1,v_P____,X0,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(X1,v_P____,X0,v_a_H____,v_a____))) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | v_a____ = X0 | v_a_H____ = X0 | v_a____ = v_a_H____) )),
  inference(forward_subsumption_resolution,[status(thm)],[f713,f604])).
fof(f723,plain,(
  ( ! [X0,X1] : (~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),X1,c_Arrow__Order__Mirabelle_OProf) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,X0),hAPP(X1,sK4(X1,v_P____,X0,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(X1,v_P____,X0,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,X0),hAPP(v_F,X1)) | v_a____ = X0 | v_a_H____ = X0) )),
  inference(forward_subsumption_resolution,[status(thm)],[f716,f614])).
fof(f762,plain,(
  ( ! [X0] : (c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,X0),hAPP(v_P_H____,sK4(v_P_H____,v_P____,X0,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,X0,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,X0),hAPP(v_F,v_P_H____)) | v_a____ = X0 | v_a_H____ = X0) )),
  inference(resolution,[status(thm)],[f723,f611])).
fof(f766,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____)))),
  inference(resolution,[status(thm)],[f762,f619])).
fof(f767,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____),
  inference(duplicate_literal_removal,[status(thm)],[f766])).
fof(f768,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f767,f704])).
fof(f769,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | v_a_H____ = v_b_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f768,f587])).
fof(f770,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_P____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____)))),
  inference(forward_subsumption_resolution,[status(thm)],[f769,f598])).
fof(f771,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____)))),
  inference(resolution,[status(thm)],[f770,f620])).
fof(f773,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a____,v_a_H____),hAPP(v_F,v_P____)) | ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(resolution,[status(thm)],[f770,f583])).
fof(f774,plain,(
  ~c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_P_H____,sK4(v_P_H____,v_P____,v_b_H____,v_a_H____,v_a____))) | c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f773,f613])).
fof(f775,plain,(
  c_member(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),c_Product__Type_OPair(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt,v_a_H____,v_b_H____),hAPP(v_F,v_P_H____)) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f774,f771])).
fof(f776,plain,(
  ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P_H____,c_Arrow__Order__Mirabelle_OProf) | ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f775,f704])).
fof(f777,plain,(
  ~c_member(tc_fun(tc_Arrow__Order__Mirabelle_Oindi,tc_fun(tc_prod(tc_Arrow__Order__Mirabelle_Oalt,tc_Arrow__Order__Mirabelle_Oalt),tc_HOL_Obool)),v_P____,c_Arrow__Order__Mirabelle_OProf) | v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f776,f611])).
fof(f778,plain,(
  v_a____ = v_b_H____ | v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f777,f604])).
fof(f779,plain,(
  v_a_H____ = v_b_H____ | v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f778,f587])).
fof(f780,plain,(
  v_a____ = v_a_H____),
  inference(forward_subsumption_resolution,[status(thm)],[f779,f598])).
fof(f781,plain,(
  $false),
  inference(forward_subsumption_resolution,[status(thm)],[f780,f614])).
% SZS output end Proof for SCT157+1
% ------------------------------
% Version: Vampire 5.0.1 (Release build, commit 3f1362b99 on 2026-07-01 15:21:00 +0200)
% Linked with Z3 4.14.0.0 3c47fd96cf5645d0c42b2c819d9e9a84380aa721 z3-4.8.4-9178-g3c47fd96c
% CaDiCaL version: 2.1.3
% Termination reason: Refutation
% Time elapsed: 0.004 s
% Peak memory usage: 12 MB
% Instructions burned: 31 (million)
% Success in time 0.04 s
