;; ============================== prooftrans ============================
;; Prover9 (64) version 2009-11A, November 2009.
;; Process 5055 was started by marty on kushiel,
;; Wed Oct 24 16:38:01 2012
;; The command was "prover9".
;; ============================== end of head ===========================

;; BEGINNING OF PROOF OBJECT
(
(1 (input) (or (P v0) (or (P v0) (or (Q v1) (Q v1)))) NIL)
(2A (propositional 1) (or (P v0) (or (Q v1) (Q v1))) NIL)
(2 (propositional 2A) (or (P v0) (Q v1)) NIL)
(3 (input) (or (not (P v0)) (not (P v1))) NIL)
(4 (input) (or (not (Q v0)) (not (Q v1))) NIL)
(10 (instantiate 3 ((v0 . v1))) (or (not (P v1)) (not (P v1))) NIL)
(11 (propositional 10) (not (P v1)) NIL)
(5 (instantiate 11 ((v1 . v0))) (not (P v0)) NIL)
(12 (instantiate 4 ((v0 . v1))) (or (not (Q v1)) (not (Q v1))) NIL)
(13 (propositional 12) (not (Q v1)) NIL)
(6 (instantiate 13 ((v1 . v0))) (not (Q v0)) NIL)
(14 (instantiate 5 ((v0 . v100))) (not (P v100)) NIL)
(15 (instantiate 2 ((v0 . v100) (v1 . v101))) (or (P v100) (Q v101)) NIL)
(16 (resolve 14 () 15 (1)) (Q v101) NIL)
(7A (instantiate 16 ((v101 . v0))) (Q v0) NIL)
(17 (instantiate 6 ((v0 . v100))) (not (Q v100)) NIL)
(18 (instantiate 7A ((v0 . v100))) (Q v100) NIL)
(7 (resolve 17 () 18 ()) false NIL)
)
;; END OF PROOF OBJECT
