;; ============================== prooftrans ============================
;; Prover9 (32) version 2009-11A, November 2009.
;; Process 24496 was started by tptp on hancock.cs.miami.edu,
;; Thu Jun 14 12:44:31 2012
;; The command was "/home/graph/tptp/Systems/Prover9---1109a/prover9 -t 300 -f /tmp/Prover9_24462_hancock.cs.miami.edu".
;; ============================== end of head ===========================

;; BEGINNING OF PROOF OBJECT
(
(281 (input) (= (c6) (c4)) NIL)
(283 (input) (neq (c4) (nil)) NIL)
(284 (input) (not (neq (c6) (nil))) NIL)
(285A (paramod 281 (1) 284 (1 1)) (not (neq (c4) (nil))) NIL)
(285 (resolve 283 () 285A ()) false NIL)
)
;; END OF PROOF OBJECT
